# Dicionário de Dados e Referências

**Dicionário de Dados de Notificação Geral - SINAN:** _http://portalsinan.saude.gov.br/images/documentos/Agravos/NINDIV/DIC_DADOS_NET_Not_Individual_rev.pdf_  
**Dicionario Ficha de Notificação Individual Geral - SINAN:** _http://portalsinan.saude.gov.br/images/documentos/Agravos/DRT%20Transtorno%20Mental/DIC_DADOS_DRT_TranstornosMentais_v5.pdf_  
**Classificação Brasileira de Ocupação:** _https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/livro-1-portal-cbo.pdf_  
**Visualizador Web - TabNet:** _http://tabnet.datasus.gov.br/cgi/tabcgi.exe?sinannet/cnv/transmentalbr.def_

_A base representa os casos notificados formalmente ao sistema de vigilância nacional, sabendo que o volume real de indivíduos com Burnout tratados por psicólogos e psiquiatras particulares/de convênio médico está altamente sub-representado nesses números._

# Instalar as dependências para o R:

In [ ]:
# 1. Instalar dependências do sistema Linux necessárias para manipulação de dados e FTP
system("apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev r-base-dev build-essential")

# 2. Instalar pacotes do R

options(repos = c(CRAN = "https://cloud.r-project.org"))

install.packages("remotes")
install.packages("rlang")
install.packages("tidyverse") # Inclui dplyr, ggplot2, etc.

# 3. Instalar o pacote microdatasus direto do repositório da Fiocruz (vai utilizar o CRAN setado anteriormente)
remotes::install_github("rfsaldanha/microdatasus", type = "source")

# 4. Carregar as bibliotecas
library("remotes")
library(microdatasus)
library(dplyr)

# As bibliotecas instaladas ficam em: /opt/conda/lib/R/library

Carregar/Verificar as bibliotecas:

In [6]:
library("remotes")
library(microdatasus)
library(dplyr)
#.libPaths()

# Baixando os dados referentes às bases SINAN para os anos de 2010 à 2025, com excessão de 2020 e 2021 (ausentes no SINAN).:

In [ ]:
anos_antigos <- "10 11 12 13 14 15 16 17 18 19"
anos_recentes <- "22 23 24 25"

system(paste("for ano in", anos_antigos, "; do wget -P ~/work ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/FINAIS/MENTBR$ano.dbc; done"))
system(paste("for ano in", anos_recentes, "; do wget -P ~/work ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/PRELIM/MENTBR$ano.dbc; done"))

#system("wget -P ~/work ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/PRELIM/MENTBR24.dbc")

library(read.dbc)
dados <- read.dbc("~/work/MENTBR25.dbc")

head(dados)

### Lendo e concatenando todos pacotes baixados referentes a cada ano:

In [ ]:
#library(read.dbc)
#library(dplyr)

# Definir os anos desejados (2010 a 2025, removendo 2020 e 2021)
anos <- 2010:2025
anos_filtrados <- anos[!anos %in% c(2020, 2021)]

# Lista vazia para armazenar os dataframes temporariamente
lista_dados <- list()

for (ano in anos_filtrados) {

  # Extrai os dois últimos dígitos do ano (ex: 2015 vira "15")
  sufixo <- substr(as.character(ano), 3, 4)

  # Monta o caminho do arquivo dinamicamente
  caminho_arquivo <- paste0("~/work/MENTBR", sufixo, ".dbc")

  # Cria um nome de identificação para a lista (ex: "ano_15")
  nome_lista <- paste0("ano_", sufixo)

  # Mensagem no console para acompanhamento do progresso da leitura
  cat("Lendo arquivo:", caminho_arquivo, "\n")

  # Lê o arquivo e armazena na lista, se existir
  if (file.exists(caminho_arquivo)) {
    lista_dados[[nome_lista]] <- read.dbc(caminho_arquivo)
  } else {
    warning(paste("Arquivo não encontrado:", caminho_arquivo))
  }
}

# Junta todos os anos em um único grande dataframe
dados_completos <- bind_rows(lista_dados, .id = "FONTE_ANO")

# Remove a lista temporária para liberar memória RAM
rm(lista_dados)

# Salvar na memória secundária
saveRDS(dados_completos, file = "work/dados_completos_sinan.rds")

# dados <- readRDS("work/dados_completos_sinan.rds")

In [5]:
dados <- readRDS("~/work/dados_completos_sinan.rds")

In [16]:
head(dados)

  FONTE_ANO TP_NOT ID_AGRAVO DT_NOTIFIC SEM_NOT NU_ANO SG_UF_NOT ID_MUNICIP
1 ano_10    2      F99       2010-01-27 201004  2010   28        280030
2 ano_10    2      F99       2010-01-29 201004  2010   42        420910
3 ano_10    2      F99       2010-01-05 201001  2010   35        355030
4 ano_10    2      F99       2010-01-26 201004  2010   29        293330
5 ano_10    2      F99       2010-01-15 201002  2010   29        292740
6 ano_10    2      F99       2010-01-15 201002  2010   29        291480
  ID_REGIONA ID_UNIDADE ⋯ ANO_NASC NU_LOTE_I DT_TRANSUS DT_TRANSDM DT_TRANSSM
1 2056       5841399    ⋯ NA       NA        <NA>       <NA>       <NA>
2 1565       2436418    ⋯ NA       NA        <NA>       <NA>       <NA>
3 1331       2786664    ⋯ NA       NA        <NA>       <NA>       <NA>
4 1398       2550202    ⋯ NA       NA        <NA>       <NA>       <NA>
5 1380       2557894    ⋯ NA       NA        <NA>       <NA>       <NA>
6 1386       3432890    ⋯ NA       NA        <NA>       <NA>       <NA>
  DT_TRANSRM DT_TRANSRS DT_TRANSSE NU_LOTE_V NU_LOTE_H
1 <NA>       <NA>       <NA>       NA        NA
2 <NA>       <NA>       <NA>       NA        NA
3 <NA>       <NA>       <NA>       NA        NA
4 <NA>       <NA>       <NA>       NA        NA
5 <NA>       <NA>       <NA>       NA        NA
6 <NA>       <NA>       <NA>       NA        NA

In [ ]:
# Explorando a base de dados coadunada:
names(dados)
length(dados)
dim(dados)

### **Averiguando variedade das categorias de transtornos mentais para a variável de Diagnóstico Específico:**

In [ ]:
dados$DIAG_ESP

### **Averiguando integridade e disponibilidade dos estados para a variável 'Estado de Notificação':**

In [ ]:
dados$SG_UF_NOT

In [8]:
# Vetor nomeado para servir de "dicionário" de tradução
tradutor_uf <- c(
  "11" = "RO", "12" = "AC", "13" = "AM", "14" = "RR", "15" = "PA", "16" = "AP", "17" = "TO",
  "21" = "MA", "22" = "PI", "23" = "CE", "24" = "RN", "25" = "PB", "26" = "PE", "27" = "AL",
  "28" = "SE", "29" = "BA", "31" = "MG", "32" = "ES", "33" = "RJ", "35" = "SP", "41" = "PR",
  "42" = "SC", "43" = "RS", "50" = "MS", "51" = "MT", "52" = "GO", "53" = "DF"
)

In [32]:
tabela_Burnout <- dados %>%
  mutate(
    UF_Codigo = trimws(as.character(SG_UF)),
    UF_SG = tradutor_uf[UF_Codigo],
  ) %>%
  filter(
    DIAG_ESP   == "Z730"
  ) %>%
  group_by(UF_SG) %>%
  summarise(Casos = n(), .groups = "drop") %>%
  arrange(UF_SG)

head(tabela_Burnout, n = Inf)

   UF_SG Casos
1  AC      4
2  AL      8
3  AM      2
4  BA    238
5  CE     64
6  DF      6
7  ES      6
8  GO      4
9  MA      7
10 MG    314
11 MS     22
12 MT      7
13 PA     11
14 PB     43
15 PE     47
16 PR     21
17 RJ     96
18 RN     51
19 RO     11
20 RR      2
21 RS     89
22 SC     78
23 SE     22
24 SP    462
25 TO     11

### Podemos verificar que não há registros referentes nem à Piauí (**PI**) nem à  Amapá (**AP**) para a base de dados utilizada.

# Selecionar as variáveis de interesse e tratar a variável de 'Estado De Notificação':

In [9]:
tabela_Burnout <- dados %>%
  select(FONTE_ANO, DIAG_ESP, SG_UF, SIT_TRAB, ID_OCUPA_N, CNAE, UF_EMP,
  TERCEIRIZA, NUTEMPORIS, TPTEMPO, AFAST_DESG, AFAST_TRAB, CAPES, EVOLUCAO, NU_IDADE_N) %>%
  mutate(
    UF_Codigo = trimws(as.character(SG_UF)),
    UF_SG = tradutor_uf[UF_Codigo],
  ) %>% select(-SG_UF, -UF_Codigo) %>%
    relocate(UF_SG, .after = DIAG_ESP) %>%
  filter(
    DIAG_ESP   == "Z730"
  )
# Exibe o resultado final com os dados tratados mediante dicionário:
#print(tabela_Burnout, n = Inf)

#saveRDS(tabela_Burnout, file = "work/dados_tratados_sinan.rds")
#tabela_Burnout <- readRDS('work/dados_tratados_sinan.rds')

head(tabela_Burnout)

  FONTE_ANO DIAG_ESP UF_SG SIT_TRAB ID_OCUPA_N CNAE  UF_EMP TERCEIRIZA
1 ano_10    Z730     SP    01       513425     NA    35     2
2 ano_10    Z730     PR    01       239405     NA    41     2
3 ano_11    Z730     MT    04       411010     NA    51     2
4 ano_11    Z730     RO    04       223405     NA    11     2
5 ano_11    Z730     BA    07       410105     NA    NA     2
6 ano_11    Z730     PE    04       331105     05126 26     2
  NUTEMPORIS TPTEMPO AFAST_DESG AFAST_TRAB CAPES EVOLUCAO NU_IDADE_N
1 5          3       1          1          1     3        4021
2 4          NA      2          1          1     3        4044
3 20         4       1          NA         1     NA       4039
4 5          4       2          2          1     3        4054
5 0          NA      1          1          1     3        4052
6 20         4       1          NA         1     4        4055

# Tratando a variável de 'Situação No Mercado De Trabalho':

In [10]:
# library(dplyr)
library(forcats)

SIT_TRAB_TRATADO <- tabela_Burnout %>%
  mutate(
    # Recodificando os níveis do fator existente
    SIT_TRAB_TRATADA = fct_recode(SIT_TRAB,
      "Empregado CLT"               = "01",
      "Empregado sem Carteira"      = "02",
      "Autônomo / Conta Própria"    = "03",
      "Trabalhador Temporário"      = "04",
      "Empregador"                  = "05",
      "Trabalhador Não Remunerado"  = "06",
      "Desempregado"                = "07",
      "Aposentado"                  = "08",
      "Ignorado"                    = "09"
    )
  )
  SIT_TRAB_TRATADO <- SIT_TRAB_TRATADO %>% relocate(SIT_TRAB_TRATADA, .after = SIT_TRAB)
  head(SIT_TRAB_TRATADO)

  #SIT_TRAB_TRATADO <- SIT_TRAB_TRATADO %>% select(-SIT_TRAB)
  #SIT_TRAB_TRATADO <- SIT_TRAB_TRATADO %>% rename(SIT_TRAB = SIT_TRAB_TRATADO)
  tabela_Burnout <- SIT_TRAB_TRATADO

  FONTE_ANO DIAG_ESP UF_SG SIT_TRAB SIT_TRAB_TRATADA       ID_OCUPA_N CNAE
1 ano_10    Z730     SP    01       Empregado CLT          513425     NA
2 ano_10    Z730     PR    01       Empregado CLT          239405     NA
3 ano_11    Z730     MT    04       Trabalhador Temporário 411010     NA
4 ano_11    Z730     RO    04       Trabalhador Temporário 223405     NA
5 ano_11    Z730     BA    07       Desempregado           410105     NA
6 ano_11    Z730     PE    04       Trabalhador Temporário 331105     05126
  UF_EMP TERCEIRIZA NUTEMPORIS TPTEMPO AFAST_DESG AFAST_TRAB CAPES EVOLUCAO
1 35     2          5          3       1          1          1     3
2 41     2          4          NA      2          1          1     3
3 51     2          20         4       1          NA         1     NA
4 11     2          5          4       2          2          1     3
5 NA     2          0          NA      1          1          1     3
6 26     2          20         4       1          NA         1     4
  NU_IDADE_N
1 4021
2 4044
3 4039
4 4054
5 4052
6 4055

# Tratando a variável de 'Ocupação':

In [11]:
# library(dplyr)
# library(forcats)

ID_OCUPA_N_TRADADO <- tabela_Burnout %>%
  mutate(
    # Garante uma versão em texto limpa (sem alterar a ID_OCUPA_N original)
    CBO_TEXTO = trimws(as.character(ID_OCUPA_N)),
    
    # Extrai os 2 primeiros dígitos (Grande Grupo)
    CBO_GRUPO_DIGITO = substr(CBO_TEXTO, 1, 2),
    
    # Traduz os Grandes Grupos com base na tabela da CBO
    CBO_GRANDE_GRUPO = case_when(
      grepl("^0", CBO_GRUPO_DIGITO) ~ "Militares, Policiais e Bombeiros",
      grepl("^1", CBO_GRUPO_DIGITO) ~ "Diretores e Gerentes",
      grepl("^2", CBO_GRUPO_DIGITO) ~ "Profissionais das Ciências e Artes (Nível Superior)",
      grepl("^3", CBO_GRUPO_DIGITO) ~ "Técnicos de Nível Médio",
      grepl("^4", CBO_GRUPO_DIGITO) ~ "Serviços Administrativos / Escritório",
      grepl("^5", CBO_GRUPO_DIGITO) ~ "Comércio, Serviços de Atendimento e Vendas",
      grepl("^6", CBO_GRUPO_DIGITO) ~ "Agropecuária, Florestal e Pesca",
      grepl("^[789]", CBO_GRUPO_DIGITO) ~ "Produção Industrial e Construção Civil",
      TRUE ~ "Não Informado / Ignorado"
    ),
    
    # Transforma o resultado final em fator para otimizar gráficos
    CBO_GRANDE_GRUPO = as.factor(CBO_GRANDE_GRUPO)
  )
  ID_OCUPA_N_TRADADO <- ID_OCUPA_N_TRADADO %>% relocate(ID_OCUPA_N, .before = CBO_TEXTO)
  # ID_OCUPA_N_TRADADO <- ID_OCUPA_N_TRADADO %>% select(-CBO_TEXTO, -CBO_GRUPO_DIGITO, -ID_OCUPA_N)
  tabela_Burnout <- ID_OCUPA_N_TRADADO
  head(tabela_Burnout)
  # saveRDS(tabela_Burnout, file = 'work/dados_tratados_sinan.rds')

  FONTE_ANO DIAG_ESP UF_SG SIT_TRAB SIT_TRAB_TRATADA       CNAE  UF_EMP
1 ano_10    Z730     SP    01       Empregado CLT          NA    35
2 ano_10    Z730     PR    01       Empregado CLT          NA    41
3 ano_11    Z730     MT    04       Trabalhador Temporário NA    51
4 ano_11    Z730     RO    04       Trabalhador Temporário NA    11
5 ano_11    Z730     BA    07       Desempregado           NA    NA
6 ano_11    Z730     PE    04       Trabalhador Temporário 05126 26
  TERCEIRIZA NUTEMPORIS TPTEMPO AFAST_DESG AFAST_TRAB CAPES EVOLUCAO NU_IDADE_N
1 2          5          3       1          1          1     3        4021
2 2          4          NA      2          1          1     3        4044
3 2          20         4       1          NA         1     NA       4039
4 2          5          4       2          2          1     3        4054
5 2          0          NA      1          1          1     3        4052
6 2          20         4       1          NA         1     4        4055
  ID_OCUPA_N CBO_TEXTO CBO_GRUPO_DIGITO
1 513425     513425    51
2 239405     239405    23
3 411010     411010    41
4 223405     223405    22
5 410105     410105    41
6 331105     331105    33
  CBO_GRANDE_GRUPO
1 Comércio, Serviços de Atendimento e Vendas
2 Profissionais das Ciências e Artes (Nível Superior)
3 Serviços Administrativos / Escritório
4 Profissionais das Ciências e Artes (Nível Superior)
5 Serviços Administrativos / Escritório
6 Técnicos de Nível Médio

# Tratando a veriável de 'Atividade Econômica Do Contratante':

In [12]:
# library(dplyr)
library(stringr)

CNAE_TRATADO <- tabela_Burnout %>%
  mutate(
    # Transforma em texto, limpa espaços e garante 5 dígitos (preenche com zero à esquerda se faltar)
    CNAE_TEXTO = str_pad(trimws(as.character(CNAE)), width = 5, side = "left", pad = "0"),

    # Extrai os 2 primeiros dígitos (A Divisão da CNAE)
    CNAE_DIVISAO = substr(CNAE_TEXTO, 1, 2),

    # Agrupa pelas Grandes Seções Econômicas mais relevantes para o Burnout/Transtornos
    CNAE_SETOR = case_when(
      CNAE_DIVISAO %in% c("45", "46", "47") ~ "Comércio Varejista e Atacadista",
      CNAE_DIVISAO %in% c("58", "59", "60", "61", "62", "63") ~ "Tecnologia, Informação e Telecom",
      CNAE_DIVISAO %in% c("64", "65", "66") ~ "Setor Financeiro e Bancário",
      CNAE_DIVISAO == "82" ~ "Serviços de Escritório e Call Center (Telemarketing)",
      CNAE_DIVISAO %in% c("86", "87", "88") ~ "Saúde Humana e Serviços Sociais",
      CNAE_DIVISAO == "85" ~ "Educação / Ensino",
      CNAE_DIVISAO %in% c("10" : "33") ~ "Indústria de Transformação",
      CNAE_DIVISAO %in% c("41", "42", "43") ~ "Construção Civil",
      TRUE ~ "Outros Setores / Não Informado"
    ),

    CNAE_SETOR = as.factor(CNAE_SETOR)
  )
  CNAE_TRATADO <- CNAE_TRATADO %>% select(-CNAE_TEXTO) %>% relocate(CNAE, .before = CNAE_DIVISAO)

  tabela_Burnout <- CNAE_TRATADO
  head(CNAE_TRATADO)

  FONTE_ANO DIAG_ESP UF_SG SIT_TRAB SIT_TRAB_TRATADA       UF_EMP TERCEIRIZA
1 ano_10    Z730     SP    01       Empregado CLT          35     2
2 ano_10    Z730     PR    01       Empregado CLT          41     2
3 ano_11    Z730     MT    04       Trabalhador Temporário 51     2
4 ano_11    Z730     RO    04       Trabalhador Temporário 11     2
5 ano_11    Z730     BA    07       Desempregado           NA     2
6 ano_11    Z730     PE    04       Trabalhador Temporário 26     2
  NUTEMPORIS TPTEMPO AFAST_DESG ⋯ CAPES EVOLUCAO NU_IDADE_N ID_OCUPA_N
1 5          3       1          ⋯ 1     3        4021       513425
2 4          NA      2          ⋯ 1     3        4044       239405
3 20         4       1          ⋯ 1     NA       4039       411010
4 5          4       2          ⋯ 1     3        4054       223405
5 0          NA      1          ⋯ 1     3        4052       410105
6 20         4       1          ⋯ 1     4        4055       331105
  CBO_TEXTO CBO_GRUPO_DIGITO
1 513425    51
2 239405    23
3 411010    41
4 223405    22
5 410105    41
6 331105    33
  CBO_GRANDE_GRUPO                                    CNAE  CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA    NA
2 Profissionais das Ciências e Artes (Nível Superior) NA    NA
3 Serviços Administrativos / Escritório               NA    NA
4 Profissionais das Ciências e Artes (Nível Superior) NA    NA
5 Serviços Administrativos / Escritório               NA    NA
6 Técnicos de Nível Médio                             05126 05
  CNAE_SETOR
1 Outros Setores / Não Informado
2 Outros Setores / Não Informado
3 Outros Setores / Não Informado
4 Outros Setores / Não Informado
5 Outros Setores / Não Informado
6 Outros Setores / Não Informado

# Tratando a veriável de 'Idade':

In [13]:
#library(dplyr)

idade_tratada <- tabela_Burnout %>%
  mutate(
    IDADE = case_when(
      substr(trimws(as.character(NU_IDADE_N)), 1, 1) == "4" ~ as.numeric(substr(trimws(as.character(NU_IDADE_N)), 2, 4)),
      substr(trimws(as.character(NU_IDADE_N)), 1, 1) %in% c("1", "2", "3") ~ 0,
      TRUE ~ NA_real_
    )
  ) %>%
  select(-NU_IDADE_N) %>% relocate(IDADE, .after = UF_SG)

tabela_Burnout <- idade_tratada

head(idade_tratada)

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA       UF_EMP
1 ano_10    Z730     SP    21    01       Empregado CLT          35
2 ano_10    Z730     PR    44    01       Empregado CLT          41
3 ano_11    Z730     MT    39    04       Trabalhador Temporário 51
4 ano_11    Z730     RO    54    04       Trabalhador Temporário 11
5 ano_11    Z730     BA    52    07       Desempregado           NA
6 ano_11    Z730     PE    55    04       Trabalhador Temporário 26
  TERCEIRIZA NUTEMPORIS TPTEMPO ⋯ AFAST_TRAB CAPES EVOLUCAO ID_OCUPA_N
1 2          5          3       ⋯ 1          1     3        513425
2 2          4          NA      ⋯ 1          1     3        239405
3 2          20         4       ⋯ NA         1     NA       411010
4 2          5          4       ⋯ 2          1     3        223405
5 2          0          NA      ⋯ 1          1     3        410105
6 2          20         4       ⋯ NA         1     4        331105
  CBO_TEXTO CBO_GRUPO_DIGITO
1 513425    51
2 239405    23
3 411010    41
4 223405    22
5 410105    41
6 331105    33
  CBO_GRANDE_GRUPO                                    CNAE  CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA    NA
2 Profissionais das Ciências e Artes (Nível Superior) NA    NA
3 Serviços Administrativos / Escritório               NA    NA
4 Profissionais das Ciências e Artes (Nível Superior) NA    NA
5 Serviços Administrativos / Escritório               NA    NA
6 Técnicos de Nível Médio                             05126 05
  CNAE_SETOR
1 Outros Setores / Não Informado
2 Outros Setores / Não Informado
3 Outros Setores / Não Informado
4 Outros Setores / Não Informado
5 Outros Setores / Não Informado
6 Outros Setores / Não Informado

# Tratando a variável de 'Estado Da Empresa'

In [31]:
UF_EMP_TRATADO <- tabela_Burnout %>%
  mutate(
    # Limpa e isola o código numérico original em formato de texto
    UF_EMP_CODIGO = trimws(as.character(UF_EMP)),

    # Cria a nova coluna traduzida buscando no dicionário
    UF_EMPRESA = tradutor_uf[UF_EMP_CODIGO],

    # Se o código não bater com nenhum estado (ou for vazio), vira "Não Informado"
    UF_EMPRESA = ifelse(is.na(UF_EMPRESA), "Não Informado / Ignorado", UF_EMPRESA),

    # Transforma em fator para manter o padrão de performance
    UF_EMPRESA = as.factor(UF_EMPRESA)
  )
  UF_EMP_TRATADO <- UF_EMP_TRATADO %>% select(-UF_EMP_CODIGO, -UF_EMP) %>% relocate(UF_EMPRESA, .before = TERCEIRIZA)
  head(UF_EMP_TRATADO)
  tabela_Burnout <- UF_EMP_TRATADO
  #saveRDS(tabela_Burnout, file = '/home/jovyan/work/dados_tratados_sinan.rds')

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA
1 ano_10    Z730     SP    21    01       Empregado CLT
2 ano_10    Z730     PR    44    01       Empregado CLT
3 ano_11    Z730     MT    39    04       Trabalhador Temporário
4 ano_11    Z730     RO    54    04       Trabalhador Temporário
5 ano_11    Z730     BA    52    07       Desempregado
6 ano_11    Z730     PE    55    04       Trabalhador Temporário
  UF_EMPRESA               TERCEIRIZA NUTEMPORIS TPTEMPO ⋯ AFAST_TRAB CAPES
1 SP                       2          5          3       ⋯ 1          1
2 PR                       2          4          NA      ⋯ 1          1
3 MT                       2          20         4       ⋯ NA         1
4 RO                       2          5          4       ⋯ 2          1
5 Não Informado / Ignorado 2          0          NA      ⋯ 1          1
6 PE                       2          20         4       ⋯ NA         1
  EVOLUCAO ID_OCUPA_N CBO_TEXTO CBO_GRUPO_DIGITO
1 3        513425     513425    51
2 3        239405     239405    23
3 NA       411010     411010    41
4 3        223405     223405    22
5 3        410105     410105    41
6 4        331105     331105    33
  CBO_GRANDE_GRUPO                                    CNAE  CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA    NA
2 Profissionais das Ciências e Artes (Nível Superior) NA    NA
3 Serviços Administrativos / Escritório               NA    NA
4 Profissionais das Ciências e Artes (Nível Superior) NA    NA
5 Serviços Administrativos / Escritório               NA    NA
6 Técnicos de Nível Médio                             05126 05
  CNAE_SETOR
1 Outros Setores / Não Informado
2 Outros Setores / Não Informado
3 Outros Setores / Não Informado
4 Outros Setores / Não Informado
5 Outros Setores / Não Informado
6 Outros Setores / Não Informado

# Tratando a variável de 'Empresa Terceirizada'

In [9]:
#library(dplyr)
library(forcats)

# Trata a variável mapeando os níveis reais do Factor e apaga a coluna original
TERCEIRIZA_TRATADO <- tabela_Burnout %>%
  mutate(
    TERCEIRIZADO = fct_recode(TERCEIRIZA,
      "Sim"           = "1",
      "Não"           = "2",
      "Não se aplica" = "3",
      "Ignorado"      = "9"
    )
  ) %>%
  select(-TERCEIRIZA) %>% relocate(TERCEIRIZADO, .after = UF_EMPRESA)
head(TERCEIRIZA_TRATADO)
tabela_Burnout <- TERCEIRIZA_TRATADO
#saveRDS(tabela_Burnout, file = '/home/jovyan/work/dados_tratados_sinan.rds')

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA
1 ano_10    Z730     SP    21    01       Empregado CLT
2 ano_10    Z730     PR    44    01       Empregado CLT
3 ano_11    Z730     MT    39    04       Trabalhador Temporário
4 ano_11    Z730     RO    54    04       Trabalhador Temporário
5 ano_11    Z730     BA    52    07       Desempregado
6 ano_11    Z730     PE    55    04       Trabalhador Temporário
  UF_EMPRESA               TERCEIRIZADO NUTEMPORIS TPTEMPO ⋯ AFAST_TRAB CAPES
1 SP                       Não          5          3       ⋯ 1          1
2 PR                       Não          4          NA      ⋯ 1          1
3 MT                       Não          20         4       ⋯ NA         1
4 RO                       Não          5          4       ⋯ 2          1
5 Não Informado / Ignorado Não          0          NA      ⋯ 1          1
6 PE                       Não          20         4       ⋯ NA         1
  EVOLUCAO ID_OCUPA_N CBO_TEXTO CBO_GRUPO_DIGITO
1 3        513425     513425    51
2 3        239405     239405    23
3 NA       411010     411010    41
4 3        223405     223405    22
5 3        410105     410105    41
6 4        331105     331105    33
  CBO_GRANDE_GRUPO                                    CNAE  CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA    NA
2 Profissionais das Ciências e Artes (Nível Superior) NA    NA
3 Serviços Administrativos / Escritório               NA    NA
4 Profissionais das Ciências e Artes (Nível Superior) NA    NA
5 Serviços Administrativos / Escritório               NA    NA
6 Técnicos de Nível Médio                             05126 05
  CNAE_SETOR
1 Outros Setores / Não Informado
2 Outros Setores / Não Informado
3 Outros Setores / Não Informado
4 Outros Setores / Não Informado
5 Outros Setores / Não Informado
6 Outros Setores / Não Informado

In [46]:
#tabela_Burnout$TERCEIRIZADO
#print(tabela_Burnout$TERCEIRIZADO)
print(table(tabela_Burnout$TERCEIRIZADO, useNA = 'ifany'))

          Sim           Não Não se aplica      Ignorado          <NA>
           91          1367            19            69            80

In [50]:
saveRDS(tabela_Burnout, file = '/home/jovyan/work/dados_tratados_sinan.rds')

# Tratando a variável de 'EVOLUCAO'

In [38]:
if(FALSE){
class(tabela_Burnout$EVOLUCAO)
table(tabela_Burnout$EVOLUCAO, useNA='ifany')
head(tabela_Burnout$EVOLUCAO)}

In [45]:
#library(dplyr)
library(forcats)

# Trata a variável EVOLUCAO, converte os níveis e descarta a original
EVOLUCAO_TRATADO <- tabela_Burnout %>%
  mutate(
    EVOLUCAO_PACIENTE = fct_recode(EVOLUCAO,
      "Cura"                                      = "1",
      "Cura não confirmada"                       = "2",
      "Incapaciade Temporária"                    = "3",
      "Incapacidade Permanente Parcial"           = "4",
      "Incapacidade Permanente Total"             = "5",
      "Óbito por doença relacionada ao trabalho" = "6",
      "Óbito por Outra Causa"                     = "7",
      "Outro"                                     = "8",
      "Ignorado"                                  = "9"
    )
  ) %>%
  select(-EVOLUCAO) %>% relocate(EVOLUCAO_PACIENTE,.after = TERCEIRIZADO)
head(EVOLUCAO_TRATADO)
tabela_Burnout <- EVOLUCAO_TRATADO

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA
1 ano_10    Z730     SP    21    01       Empregado CLT
2 ano_10    Z730     PR    44    01       Empregado CLT
3 ano_11    Z730     MT    39    04       Trabalhador Temporário
4 ano_11    Z730     RO    54    04       Trabalhador Temporário
5 ano_11    Z730     BA    52    07       Desempregado
6 ano_11    Z730     PE    55    04       Trabalhador Temporário
  UF_EMPRESA               TERCEIRIZADO EVOLUCAO_PACIENTE
1 SP                       Não          Incapaciade Temporária
2 PR                       Não          Incapaciade Temporária
3 MT                       Não          NA
4 RO                       Não          Incapaciade Temporária
5 Não Informado / Ignorado Não          Incapaciade Temporária
6 PE                       Não          Incapacidade Permanente Parcial
  NUTEMPORIS ⋯ AFAST_DESG AFAST_TRAB CAPES ID_OCUPA_N CBO_TEXTO
1 5          ⋯ 1          1          1     513425     513425
2 4          ⋯ 2          1          1     239405     239405
3 20         ⋯ 1          NA         1     411010     411010
4 5          ⋯ 2          2          1     223405     223405
5 0          ⋯ 1          1          1     410105     410105
6 20         ⋯ 1          NA         1     331105     331105
  CBO_GRUPO_DIGITO CBO_GRANDE_GRUPO                                    CNAE
1 51               Comércio, Serviços de Atendimento e Vendas          NA
2 23               Profissionais das Ciências e Artes (Nível Superior) NA
3 41               Serviços Administrativos / Escritório               NA
4 22               Profissionais das Ciências e Artes (Nível Superior) NA
5 41               Serviços Administrativos / Escritório               NA
6 33               Técnicos de Nível Médio                             05126
  CNAE_DIVISAO CNAE_SETOR
1 NA           Outros Setores / Não Informado
2 NA           Outros Setores / Não Informado
3 NA           Outros Setores / Não Informado
4 NA           Outros Setores / Não Informado
5 NA           Outros Setores / Não Informado
6 05           Outros Setores / Não Informado

# Tratando a  variável de 'Tempo de Trabalho Na Ocupação'

In [159]:
#library(dplyr)
#library(forcats)

# Trata a variável TPTEMPO, converte os níveis e descarta a original
TPTEMPO_TRATADO <- tabela_Burnout %>%
  mutate(
    TPTEMPO_TRADUZIDO = fct_recode(TPTEMPO,
      "Horas" = "1",
      "Dias"  = "2",
      "Meses" = "3",
      "Anos"  = "4"
    )
  )
#table(TPTEMPO_TRATADO$TPTEMPO_TRADUZIDO, useNA='ifany')
tabela_Burnout <- TPTEMPO_TRATADO
head(TPTEMPO_TRATADO)

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA
1 ano_10    Z730     SP    21    01       Empregado CLT
2 ano_10    Z730     PR    44    01       Empregado CLT
3 ano_11    Z730     MT    39    04       Trabalhador Temporário
4 ano_11    Z730     RO    54    04       Trabalhador Temporário
5 ano_11    Z730     BA    52    07       Desempregado
6 ano_11    Z730     PE    55    04       Trabalhador Temporário
  UF_EMPRESA               TERCEIRIZADO EVOLUCAO_PACIENTE
1 SP                       Não          Incapaciade Temporária
2 PR                       Não          Incapaciade Temporária
3 MT                       Não          NA
4 RO                       Não          Incapaciade Temporária
5 Não Informado / Ignorado Não          Incapaciade Temporária
6 PE                       Não          Incapacidade Permanente Parcial
  NUTEMPORIS ⋯ AFAST_TRAB CAPES ID_OCUPA_N CBO_TEXTO CBO_GRUPO_DIGITO
1 5          ⋯ 1          1     513425     513425    51
2 4          ⋯ 1          1     239405     239405    23
3 20         ⋯ NA         1     411010     411010    41
4 5          ⋯ 2          1     223405     223405    22
5 0          ⋯ 1          1     410105     410105    41
6 20         ⋯ NA         1     331105     331105    33
  CBO_GRANDE_GRUPO                                    CNAE  CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA    NA
2 Profissionais das Ciências e Artes (Nível Superior) NA    NA
3 Serviços Administrativos / Escritório               NA    NA
4 Profissionais das Ciências e Artes (Nível Superior) NA    NA
5 Serviços Administrativos / Escritório               NA    NA
6 Técnicos de Nível Médio                             05126 05
  CNAE_SETOR                     TPTEMPO_TRADUZIDO
1 Outros Setores / Não Informado Meses
2 Outros Setores / Não Informado NA
3 Outros Setores / Não Informado Anos
4 Outros Setores / Não Informado Anos
5 Outros Setores / Não Informado NA
6 Outros Setores / Não Informado Anos

In [142]:
tabela_Burnout <- readRDS('/home/jovyan/work/dados_tratados_sinan.rds')

In [3]:
head(tabela_Burnout,3)

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA       UF_EMPRESA
1 ano_10    Z730     SP    21    01       Empregado CLT          SP
2 ano_10    Z730     PR    44    01       Empregado CLT          PR
3 ano_11    Z730     MT    39    04       Trabalhador Temporário MT
  TERCEIRIZADO EVOLUCAO_PACIENTE      NUTEMPORIS ⋯ AFAST_DESG AFAST_TRAB CAPES
1 Não          Incapaciade Temporária 5          ⋯ 1          1          1
2 Não          Incapaciade Temporária 4          ⋯ 2          1          1
3 Não          NA                     20         ⋯ 1          NA         1
  ID_OCUPA_N CBO_TEXTO CBO_GRUPO_DIGITO
1 513425     513425    51
2 239405     239405    23
3 411010     411010    41
  CBO_GRANDE_GRUPO                                    CNAE CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA   NA
2 Profissionais das Ciências e Artes (Nível Superior) NA   NA
3 Serviços Administrativos / Escritório               NA   NA
  CNAE_SETOR
1 Outros Setores / Não Informado
2 Outros Setores / Não Informado
3 Outros Setores / Não Informado

In [160]:
table(tabela_Burnout$TPTEMPO, useNA='ifany')
table(tabela_Burnout$NUTEMPORIS, useNA='ifany')

   2    3    4    1 <NA>
   2  133 1269   10  212

  0   1  10  11  12  13  14  15  17  18  19   2  20  21  22  23  24  25  26  27
270 114  65  31  39  37  39  44  34  35  19 152  35  16  12  13  13   8   5  10
 28  29   3  30  31  32  34  35   4  40  44   5  50   6  60   7   8   9  16  36
  3   6 118   7   4   5   5   4  92   3   0  88   1  65   1  62  73  55  34   0
 39  43  33  42  45  47  64  82  41  37  51  63  90  46  99  38  48  66  54  56
  4   0   4   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 78  49  71  96  53  75  52  57  68  70  73
  0   0   0   0   0   0   0   0   0   0   0

In [161]:
teste <- tabela_Burnout %>%
select(TPTEMPO, NUTEMPORIS) %>%
mutate(NUTEMPORIS = as.numeric(as.character(NUTEMPORIS))) %>%
filter(!is.na(NUTEMPORIS) & NUTEMPORIS > 31)
head(teste)
unique(tabela_Burnout$NUTEMPORIS)
#class(tabela_Burnout$NUTEMPORIS)

  TPTEMPO NUTEMPORIS
1 4       32
2 4       39
3 4       40
4 4       35
5 4       40
6 4       34

 [1] 5  4  20 0  9  17 24 32 11 3  14 19 22 6  8  18 1  2  39 40 15 7  13 23 10
[26] 25 35 12 27 21 29 28 30 34 16 31 26 33 42 60 50
71 Levels: 0 1 10 11 12 13 14 15 17 18 19 2 20 21 22 23 24 25 26 27 28 29 ... 73

# Tratando a variável de 'Tempo De Exposição Ao Agente De Risco'

In [165]:
#library(dplyr)
library(stringr)

# Tratamento completo e unificação da NUTEMPORIS em Anos
NUTEMPORIS_TRATADO <- tabela_Burnout %>%
  mutate(
    # 1. Isola o valor numérico puro da NUTEMPORIS (lidando com números curtos e máscaras)
    TEMPO_BRUTO = trimws(as.character(NUTEMPORIS)),
    TEMPO_NUMERICO = case_when(
      nchar(TEMPO_BRUTO) == 4 & substr(TEMPO_BRUTO, 1, 1) %in% c("1","2","3","4") ~ as.numeric(substr(TEMPO_BRUTO, 2, 4)),
      TRUE ~ as.numeric(TEMPO_BRUTO) # Captura os valores puros como 5, 20, 3
    ),
    
    # 2. Resgata o código original da TPTEMPO para fazer o cálculo preciso
    UNIDADE_COD = trimws(as.character(TPTEMPO)),
    
    # 3. Faz a conversão matemática exata para Anos com base na unidade
    TEMPO_EXPOSICAO_ANOS = case_when(
      UNIDADE_COD == "4" ~ TEMPO_NUMERICO,                       # Já está em anos
      UNIDADE_COD == "3" ~ round(TEMPO_NUMERICO / 12, 2),        # Meses -> Anos (arredondado para 2 casas)
      UNIDADE_COD == "2" ~ round(TEMPO_NUMERICO / 365, 2),       # Dias -> Anos
      UNIDADE_COD == "1" ~ round(TEMPO_NUMERICO / (365*24), 5),  # Horas
      TRUE ~ NA_real_                                            # Ignorados ou inconsistências
    )
  ) %>%
  # Limpando o dataframe, deletando as variáveis originais e intermediárias
  select(-NUTEMPORIS, if(FALSE){-TPTEMPO}, -TEMPO_BRUTO, -TEMPO_NUMERICO, -UNIDADE_COD)
tabela_Burnout<-NUTEMPORIS_TRATADO
head(NUTEMPORIS_TRATADO)

  FONTE_ANO DIAG_ESP UF_SG IDADE SIT_TRAB SIT_TRAB_TRATADA
1 ano_10    Z730     SP    21    01       Empregado CLT
2 ano_10    Z730     PR    44    01       Empregado CLT
3 ano_11    Z730     MT    39    04       Trabalhador Temporário
4 ano_11    Z730     RO    54    04       Trabalhador Temporário
5 ano_11    Z730     BA    52    07       Desempregado
6 ano_11    Z730     PE    55    04       Trabalhador Temporário
  UF_EMPRESA               TERCEIRIZADO EVOLUCAO_PACIENTE               TPTEMPO
1 SP                       Não          Incapaciade Temporária          3
2 PR                       Não          Incapaciade Temporária          NA
3 MT                       Não          NA                              4
4 RO                       Não          Incapaciade Temporária          4
5 Não Informado / Ignorado Não          Incapaciade Temporária          NA
6 PE                       Não          Incapacidade Permanente Parcial 4
  ⋯ CAPES ID_OCUPA_N CBO_TEXTO CBO_GRUPO_DIGITO
1 ⋯ 1     513425     513425    51
2 ⋯ 1     239405     239405    23
3 ⋯ 1     411010     411010    41
4 ⋯ 1     223405     223405    22
5 ⋯ 1     410105     410105    41
6 ⋯ 1     331105     331105    33
  CBO_GRANDE_GRUPO                                    CNAE  CNAE_DIVISAO
1 Comércio, Serviços de Atendimento e Vendas          NA    NA
2 Profissionais das Ciências e Artes (Nível Superior) NA    NA
3 Serviços Administrativos / Escritório               NA    NA
4 Profissionais das Ciências e Artes (Nível Superior) NA    NA
5 Serviços Administrativos / Escritório               NA    NA
6 Técnicos de Nível Médio                             05126 05
  CNAE_SETOR                     TPTEMPO_TRADUZIDO TEMPO_EXPOSICAO_ANOS
1 Outros Setores / Não Informado Meses              0.42
2 Outros Setores / Não Informado NA                   NA
3 Outros Setores / Não Informado Anos              20.00
4 Outros Setores / Não Informado Anos               5.00
5 Outros Setores / Não Informado NA                   NA
6 Outros Setores / Não Informado Anos              20.00

### Verificando a desdiscretização da variável 'TEMPO_EXPOSICAO_ANOS'

In [163]:
test<-NUTEMPORIS_TRATADO%>%
select(TPTEMPO, TEMPO_EXPOSICAO_ANOS)%>%
filter(TEMPO_EXPOSICAO_ANOS < 1 & TEMPO_EXPOSICAO_ANOS!=0)
head(test3)

  TPTEMPO TEMPO_EXPOSICAO_ANOS
1 3       0.4200
2 3       0.2500
3 1       0.0008
4 3       0.7500
5 3       0.7500
6 3       0.7500

### Verificando escala da variável para o armazenamento do tempo em horas

In [168]:
test<-NUTEMPORIS_TRATADO%>%
select(TPTEMPO, TEMPO_EXPOSICAO_ANOS)%>%
filter(TPTEMPO == 1 & TEMPO_EXPOSICAO_ANOS != 0)
head(test,10)

  TPTEMPO TEMPO_EXPOSICAO_ANOS
1 1       0.00080
2 1       0.00034
3 1       0.00068
4 1       0.00034
5 1       0.00091
6 1       0.00194
7 1       0.00023