# Dicionário de Dados e Referências

**Dicionário de Dados de Notificação Geral - SINAN:** _http://portalsinan.saude.gov.br/images/documentos/Agravos/NINDIV/DIC_DADOS_NET_Not_Individual_rev.pdf_  
**Dicionario Ficha de Notificação Individual Geral - SINAN:** _http://portalsinan.saude.gov.br/images/documentos/Agravos/DRT%20Transtorno%20Mental/DIC_DADOS_DRT_TranstornosMentais_v5.pdf_  
**Classificação Brasileira de Ocupação:** _https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/livro-1-portal-cbo.pdf_  
**Visualizador Web - TabNet:** _http://tabnet.datasus.gov.br/cgi/tabcgi.exe?sinannet/cnv/transmentalbr.def_

# Instalar as dependências para o R:

In [ ]:
# 1. Instalar dependências do sistema Linux necessárias para manipulação de dados e FTP
system("apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev r-base-dev build-essential")

# 2. Instalar pacotes do R

options(repos = c(CRAN = "https://cloud.r-project.org"))

install.packages("remotes")
install.packages("rlang")
install.packages("tidyverse") # Inclui dplyr, ggplot2, etc.

# 3. Instalar o pacote microdatasus direto do repositório da Fiocruz (vai utilizar o CRAN setado anteriormente)
remotes::install_github("rfsaldanha/microdatasus", type = "source")

# 4. Carregar as bibliotecas
library("remotes")
library(microdatasus)
library(dplyr)

# As bibliotecas instaladas ficam em: /opt/conda/lib/R/library

Carregar/Verificar as bibliotecas:

In [8]:
library("remotes")
library(microdatasus)
library(dplyr)
#.libPaths()

# Baixando os dados referentes às bases SINAN para os anos de 2010 à 2025, com excessão de 2020 e 2021 (ausentes no SINAN).:

In [ ]:
anos_antigos <- "10 11 12 13 14 15 16 17 18 19"
anos_recentes <- "22 23 24 25"

system(paste("for ano in", anos_antigos, "; do wget -P ~/work ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/FINAIS/MENTBR$ano.dbc; done"))
system(paste("for ano in", anos_recentes, "; do wget -P ~/work ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/PRELIM/MENTBR$ano.dbc; done"))

#system("wget -P ~/work ftp://ftp.datasus.gov.br/dissemin/publicos/SINAN/DADOS/PRELIM/MENTBR24.dbc")

library(read.dbc)
dados <- read.dbc("~/work/MENTBR25.dbc")

head(dados)

Lendo e concatenando todos pacotes baixados referentes a cada ano:

In [ ]:
#library(read.dbc)
#library(dplyr)

# 1. Definir os anos que queremos (2010 a 2025, removendo 2020 e 2021)
anos <- 2010:2025
anos_filtrados <- anos[!anos %in% c(2020, 2021)]

# 2. Criar uma lista vazia para armazenar os dataframes temporariamente
lista_dados <- list()

# 3. O Laço de Repetição
for (ano in anos_filtrados) {

  # Extrai os dois últimos dígitos do ano (ex: 2015 vira "15")
  sufixo <- substr(as.character(ano), 3, 4)

  # Monta o caminho do arquivo dinamicamente
  caminho_arquivo <- paste0("~/work/MENTBR", sufixo, ".dbc")

  # Cria um nome de identificação para a lista (ex: "ano_15")
  nome_lista <- paste0("ano_", sufixo)

  # Mensagem no console para você acompanhar o progresso da leitura
  cat("Lendo arquivo:", caminho_arquivo, "\n")

  # Lê o arquivo e armazena na lista se ele existir
  if (file.exists(caminho_arquivo)) {
    lista_dados[[nome_lista]] <- read.dbc(caminho_arquivo)
  } else {
    warning(paste("Arquivo não encontrado:", caminho_arquivo))
  }
}

# 4. Junta todos os anos em um único grande dataframe
dados_completos <- bind_rows(lista_dados, .id = "FONTE_ANO")

# Remove a lista temporária para liberar memória RAM
rm(lista_dados)

# Salvando na memória secundária
saveRDS(dados_completos, file = "work/dados_completos_sinan.rds")

# dados <- readRDS("work/dados_completos_sinan.rds")

In [12]:
dados <- readRDS("~/work/dados_completos_sinan.rds")

In [13]:
head(dados)

  FONTE_ANO TP_NOT ID_AGRAVO DT_NOTIFIC SEM_NOT NU_ANO SG_UF_NOT ID_MUNICIP
1 ano_10    2      F99       2010-01-27 201004  2010   28        280030
2 ano_10    2      F99       2010-01-29 201004  2010   42        420910
3 ano_10    2      F99       2010-01-05 201001  2010   35        355030
4 ano_10    2      F99       2010-01-26 201004  2010   29        293330
5 ano_10    2      F99       2010-01-15 201002  2010   29        292740
6 ano_10    2      F99       2010-01-15 201002  2010   29        291480
  ID_REGIONA ID_UNIDADE ⋯ ANO_NASC NU_LOTE_I DT_TRANSUS DT_TRANSDM DT_TRANSSM
1 2056       5841399    ⋯ NA       NA        <NA>       <NA>       <NA>
2 1565       2436418    ⋯ NA       NA        <NA>       <NA>       <NA>
3 1331       2786664    ⋯ NA       NA        <NA>       <NA>       <NA>
4 1398       2550202    ⋯ NA       NA        <NA>       <NA>       <NA>
5 1380       2557894    ⋯ NA       NA        <NA>       <NA>       <NA>
6 1386       3432890    ⋯ NA       NA        <NA>       <NA>       <NA>
  DT_TRANSRM DT_TRANSRS DT_TRANSSE NU_LOTE_V NU_LOTE_H
1 <NA>       <NA>       <NA>       NA        NA
2 <NA>       <NA>       <NA>       NA        NA
3 <NA>       <NA>       <NA>       NA        NA
4 <NA>       <NA>       <NA>       NA        NA
5 <NA>       <NA>       <NA>       NA        NA
6 <NA>       <NA>       <NA>       NA        NA

In [18]:
# Explorando a base de dados coadunada:
names(dados)
length(dados)
dim(dados)

 [1] "FONTE_ANO"  "TP_NOT"     "ID_AGRAVO"  "DT_NOTIFIC" "SEM_NOT"
 [6] "NU_ANO"     "SG_UF_NOT"  "ID_MUNICIP" "ID_REGIONA" "ID_UNIDADE"
[11] "DT_DIAG"    "SEM_DIAG"   "NU_IDADE_N" "CS_SEXO"    "CS_GESTANT"
[16] "CS_RACA"    "CS_ESCOL_N" "SG_UF"      "ID_MN_RESI" "ID_RG_RESI"
[21] "ID_PAIS"    "ID_OCUPA_N" "SIT_TRAB"   "NUTEMPO"    "TPTEMPO"
[26] "CNAE"       "UF_EMP"     "MUN_EMP"    "TERCEIRIZA" "NUTEMPORIS"
[31] "TPTEMPORIS" "REGIME"     "DIAG_ESP"   "ALCOOL"     "PSICO_FARM"
[36] "DROGAS"     "FUMA"       "TEMPO_FUMA" "TP_TEMP_FU" "AFAST_DESG"
[41] "INDIVIDUAL" "MUDA_TRAB"  "NENHUM"     "COLETIVA"   "AFAST_TRAB"
[46] "CONDUTA"    "TRAB_DOE"   "CAPES"      "DT_OBITO"   "CAT"
[51] "EVOLUCAO"   "CONDUT_DES" "DT_DIGITA"  "ANO_NASC"   "NU_LOTE_I"
[56] "DT_TRANSUS" "DT_TRANSDM" "DT_TRANSSM" "DT_TRANSRM" "DT_TRANSRS"
[61] "DT_TRANSSE" "NU_LOTE_V"  "NU_LOTE_H"

[1] 63

[1] 26873    63

**Averiguando variedade das categorias de transtornos mentais para a variável de Diagnóstico Específico:**

In [15]:
dados$DIAG_ESP

    [1] F419 F43  F333 F431 F99  F432 F432 F432 F412 F332 F430 F432 F432 F32
   [15] F32  F32  F431 F322 F430 F333 F454 F32  F413 F431 F32  F38  F330 F332
   [29] F431 F410 F431 F431 F321 Z730 Z578 F329 F321 F43  F43  F29  <NA> F32
   [43] F313 F41  F32  F321 F332 F412 F438 F432 F432 F323 F431 <NA> F409 F410
   [57] F331 F321 F432 F321 F333 F331 F431 F431 <NA> F431 F431 F43  F99  F411
   [71] F41  F432 F431 F99  F412 F332 F431 F432 <NA> F432 F322 F43  F431 F321
   [85] F43  F411 F43  F43  F32  F412 F32  F42  F431 F431 F431 F322 F32  F32
   [99] F31  F431 F333 F430 F320 F41  F32  F32  I50  F321 F430 F209 F431 F322
  [113] F43  <NA> F320 F431 F321 F329 F322 F51  F431 F431 F329 F33  F438 F43
  [127] F430 F43  F322 F431 F32  F32  F32  F431 T434 F32  F32  F32  F43  F70
  [141] <NA> F339 F431 F32  <NA> F411 F40  F332 F420 F332 F412 F419 F321 F321
  [155] <NA> <NA> F43  F430 F43  F99  F07  F43  F20  F41  F512 <NA> F322 Z56
  [169] <NA> F41  F99  F422 F322 F410 F43  F231 F432 F431 <NA> F430 F43  F432
  [183] F411 <NA> F32  F333 F320 F410 F43  F431 F321 F432 H903 F51  F32  F431
  [197] F431 F322 F431 F431 F430 F41  F322 F323 F322 F432 F321 F43  F432 G47
  [211] F322 F409 Z565 F33  F40  F322 F48  F43  F438 Z565 F32  F32  F99  F411
  [225] F432 F348 F328 F40  F321 F322 F432 F431 F431 <NA> F411 F320 F41  F41
  [239] F41  F41  F410 F32  F31  <NA> F32  F322 F431 F43  F33  F42  F431 F430
  [253] F99  F40  F431 F43  F332 F99  F99  F412 F431 F43  F322 F380 F41  F322
  [267] F321 F329 F32  F431 F431 F32  F431 F431 F431 F410 F431 F410 <NA> F078
  [281] F43  F410 F432 F41  F072 Z730 F411 F33  F439 F322 F430 F431 F40  F412
  [295] F43  F43  F438 F431 F438 F488 F43  S43  F99  F99  F99  F430 F431 F331
  [309] F322 F32  F43  F320 F320 F99  F32  F42  F329 F32  F411 F410 F419 F419
  [323] F412 F431 F322 F99  F32  <NA> <NA> F431 F412 F322 F33  F412 F431 F32
  [337] F32  F412 F412 F431 F412 F321 <NA> F438 F323 F438 F41  F331 F412 F322
  [351] F33  F431 F431 F32  F430 F431 <NA> F430 F431 F431 F431 F431 F431 F99
  [365] F322 F32  F32  F321 F431 F43  F32  F322 <NA> F432 F432 F431 <NA> <NA>
  [379] F32  F99  F410 F32  <NA> F512 F432 F33  F322 <NA> F410 F412 F432 F432
  [393] F41  F32  F32  F43  F431 F43  F43  F412 F412 F322 F32  F99  F431 F43
  [407] F233 F431 F431 F430 F401 F419 <NA> F322 F43  F45  F412 F32  F430 F32
  [421] <NA> F431 F43  F41  F430 F430 <NA> F412 F431 <NA> <NA> Z730 F431 <NA>
  [435] F300 F321 F43  <NA> <NA> F43  F41  F320 F410 <NA> <NA> F322 F402 <NA>
  [449] F32  <NA> Z566 F20  F432 F419 <NA> F32  F454 F430 F431 F431 F412 F410
  [463] F431 F431 F430 F431 F431 F432 F431 F431 F430 F300 F32  F32  T431 F431
  [477] F438 Z73  F431 F431 F32  Z566 F432 F332 F32  F43  <NA> <NA> F439 F430
  [491] F430 F430 F430 F430 F430 F430 F430 F430 F430 F430 F430 F430 F430 F430
  [505] F430 F99  F32  F411 F43  F432 F322 F439 F43  F41  I10  <NA> F322 F432
  [519] F32  F430 F32  F03  F30  F430 F322 <NA> F43  F43  F412 F20  F41  F32
  [533] F32  F321 F322 F43  Z730 Z565 F431 <NA> F43  F430 F430 F431 F321 <NA>
  [547] F320 F412 F40  Z730 F32  F44  F448 F411 F31  F32  F410 F322 F43  F411
  [561] F32  F402 Z609 F332 F431 F322 F322 F43  F431 F431 F32  F99  F99  F99
  [575] F99  F99  F99  Z730 F410 F330 F431 <NA> <NA> F43  <NA> F431 F43  F439
  [589] F99  F232 F430 F431 F333 F321 F32  F41  F321 F320 F411 <NA> F32  Z730
  [603] Z730 F322 F322 F318 F32  F321 F43  F32  F410 F320 F99  F99  F431 F432
  [617] F32  F432 F431 <NA> F438 F431 F422 F321 F323 F431 F410 F431 F32  F431
  [631] F43  F432 <NA> F063 F410 F431 F432 F411 <NA> F322 F412 F41  F43  F431
  [645] F432 Z565 F321 F43  F43  F99  F32  F32  F41  F410 <NA> F33  F410 F43
  [659] F32  F43  F438 F412 F450 <NA> F431 F412 F431 F431 F431 F99  F412 F40
  [673] <NA> <NA> F43  F412 F431 F432 F431 F43  F322 F450 F42  F431 F99  <NA>
  [687] F41  F43  F430 F31  F321 F43  F488 F431 F431 F432 F331 F412 F43  F99
  [701] F99  F99  F99  <NA> F431 F329 <NA> F332 F99  F99  F99  F43  F430 F419
  [715] F432 F430 F431 <NA> F431 F431 F314 F431 F431 F431 <NA> F43  F431 F231
  [729] F331 F321 F410 <NA> <NA> <NA> F432 F320 F412 F320 F432 F32  F431 F41
  [743] F412 <NA> F331 F338 F332 <NA> F43  F322 F322 F408 F322 F06  F430 F432
  [757] F412 F430 <NA> F430 F430 F488 F411 F410 F32  F99  F320 F99  F43  F412
  [771] F411 <NA> Z730 F432 F32  F43  F29  F322 F32  F320 F10  F432 F99  F99
  [785] F99  F320 F911 F411 F99  F331 F32  F411 F320 F32  F43  F32  F10  F32
  [799] F10  F410 F10  F322 F432 F10  F430 F43  F329 F322 F322 <NA> F430 <NA>
  [813] F431 F322 F321 F320 F412 F43  F43  F99  F431 F328 F333 F102 F920 F430
  [827] F512 F32  F439 F411 F411 F32  F431 F314 F320 F412 <NA> <NA> <NA> F99
  [841] F333 F422 F321 F43  <NA> <NA> F411 F431 F488 F311 Z73  F439 F432 F431
  [855] F431 F431 F430 F431 F32  F328 <NA> F323 F412 F412 F431 F43  F431 Z730
  [869] F43  F431 F410 <NA> F332 F99  F431 F328 F431 F322 F43  F99  F412 F323
  [883] F431 F99  F41  F331 F40  F412 F432 F431 F412 F418 F322 F431 F431 F43
  [897] F322 F321 F412 F411 F43  F322 F21  F431 F431 F99  F41  F322 F419 F321
  [911] F412 F432 Z73  F43  F32  F430 F332 F43  <NA> F32  F21  F117 F322 F322
  [925] F32  F320 F320 F401 F195 F320 F320 F195 F412 F200 F419 F41  F43  F430
  [939] Z65  F431 <NA> F99  F412 F431 <NA> F430 F43  <NA> F431 F43  F31  Z730
  [953] F412 <NA> F99  F99  F431 <NA> <NA> <NA> F431 F41  F431 F320 F430 F518
  [967] <NA> <NA> <NA> <NA> F99  F432 F430 F99  F99  F99  F43  F20  F323 F34
  [981] F322 Z56  F411 F431 F32  F430 F410 F200 F329 F411 F332 Z566 F323 F432
  [995] F430 F411 <NA> <NA> F329 F412 F322 F321 F411 F411 F431 F43  F431 F431
 [1009] <NA> Z57  F411 <NA> F322 F431 F323 F32  F432 F332 F321 F412 F322 F322
 [1023] F328 F43  F431 F43  F43  F43  F333 F410 F84  F40  F430 F43  F431 <NA>
 [1037] <NA> Z506 F316 F99  F411 F430 F431 F41  F431 F321 F43  F411 F32  F31
 [1051] F32  F32  F431 Z730 F410 F332 F331 F431 F439 F439 Z73  F323 F411 F321
 [1065] F32  F315 F43  <NA> F731 F43  F329 F322 F32  F431 F99  F99  F99  <NA>
 [1079] F99  F431 F43  F322 <NA> <NA> F99  F43  F332 <NA> F430 F432 F41  F322
 [1093] F321 F321 F321 F32  F32  F320 F43  F41  F432 <NA> F321 F431 F431 F32
 [1107] F43  Z51  F33  F430 F431 F430 F322 F321 F431 F322 F321 F311 <NA> <NA>
 [1121] F432 F431 F410 F431 F322 F431 F322 F99  F412 F410 F31  F322 F323 F99
 [1135] F432 F512 F412 F431 F432 F412 F431 F410 F43  F432 F430 F078 F331 F43
 [1149] F43  F430 F432 F430 F40  F432 F410 R450 R450 F412 F321 F412 Z73  R450
 [1163] F33  F31  F322 F432 F412 F412 Z730 F430 Z033 Z233 F411 F512 F99  F412
 [1177] F333 F410 F323 F411 F410 M54  F431 F322 F410 F322 F431 F43  F322 F431
 [1191] F430 F432 F328 F410 F431 F431 F410 F431 F412 F431 F412 F43  F43  F43
 [1205] F332 F322 F43  F322 F332 F432 F410 Z730 <NA> F412 F322 F32  F431 F412
 [1219] F408 F43  F431 F331 F332 <NA> F41  F331 F432 F43  F43  F99  F431 S01
 [1233] F332 Z566 <NA> F410 F322 R450 F410 F43  <NA> F32  F321 F412 F439 F438
 [1247] F33  F41  F33  F412 F431 F323 F43  F431 F431 F32  F412 F322 F321 F43
 [1261] F431 F431 F418 F41  F432 F323 F430 F321 F480 F412 F321 F411 F412 <NA>
 [1275] F43  Z566 <NA> F200 F40  F412 F322 F321 F32  F419 F102 F329 F321 F43
 [1289] F431 F412 F430 F43  F322 F329 F410 F431 <NA> F431 F332 F32  F33  F431
 [1303] F34  F431 F43  F322 F60  Z566 <NA> F431 F328 F431 F322 F323 <NA> F332
 [1317] F451 F431 F322 F431 F41  F316 F331 <NA> F333 F431 F32  F431 F322 F488
 [1331] F323 <NA> F430 F431 F321 F259 F20  F412 F421 F431 F430 F430 F43  F410
 [1345] F412 F431 F412 <NA> F412 F411 F321 F431 F322 Z730 F430 F431 Z565 F43
 [1359] F412 F431 F43  F431 F99  F063 F43  <NA> F32  F432 Z730 F401 F99  F329
 [1373] F41  F41  <NA> F431 T609 F331 F322 F32  F321 F41  F431 F323 F412 F438
 [1387] Z730 F43  F432 F33  Z562 <NA> G64  Z73  Z566 F411 F431 F33  F438 F412
 [1401] F430 F430 F431 F430 F430 F321 F99  <NA> F43  F331 F400 F412 F43  F41
 [1415] F32  F43  F331 F32  F432 <NA> I10  F430 F431 F32  F430 F412 F431 F32
 [1429] F42  F321 F432 F316 F31  F410 F431 F412 F431 F32  F322 Z730 F33  F430
 [1443] F43  F41  F431 F431 F430 F431 F431 F412 F431 F333 F413 F430 F430 F322
 [1457] F43  F431 F32  F488 F42  F332 <NA> F332 F412 F430 F322 F43  F43  F322
 [1471] F321 F322 <NA> F338 F32  F32  F32  F412 F320 F43  F32  F43  F331 F99
 [1485] F43  <NA> F432 F33  F431 F411 F413 F339 F431 F43  F432 F310 F341 F99
 [1499] <NA> F43  F32  F062 F43  F432 <NA> F410 F209 F412 F10  F430 F320 F411
 [1513] <NA> F32  F41  M751 F33  F43  F334 <NA> F32  <NA> <NA> F432 <NA> F32
 [1527] F99  <NA> <NA> F99  F321 F32  F321 F410 F317 F332 F431 Z73  F412 F322
 [1541] F412 F332 F431 F431 F431 M77  M75  F43  F432 F331 F412 F40  F32  F341
 [1555] F431 F432 F323 F419 F412 F412 F332 F322 F438 F431 F320 R450 F431 F430
 [1569] F431 F431 F432 F432 F432 F410 F431 F431 F43  R450 F32  F431 F430 <NA>
 [1583] F32  F45  <NA> F431 F431 F99  F432 F322 F329 F43  F431 F431 F323 <NA>
 [1597] F43  F432 F321 F432 F431 F432 F323 Z730 F412 F412 F412 F431 F410 Z56
 [1611] F231 <NA> F99  F410 S933 Z567 F43  <NA> F430 F430 F322 F431 F432 F322
 [1625] F41  F73  F412 F43  F432 F431 F431 F431 F412 F431 F410 F412 F43  F432
 [1639] F432 F431 F41  F431 F431 F322 <NA> F43  F431 F41  F32  F322 F431 F32
 [1653] F432 F412 F32  F431 F431 F432 F32  F431 F431 F32  <NA> F432 F43  F331
 [1667] F431 Z565 F333 F430 F431 R457 F25  F322 F431 F411 F412 F43  F43  F43
 [1681] F412 F43  F410 F34  F321 F322 F32  F32  F99  Z730 F431 F431 F99  F43
 [1695] F430 F440 F430 F432 F431 F431 F32  F32  F32  F99  F322 F323 F10  F322
 [1709] F32  F32  F32  <NA> F323 F438 S069 W13  F431 F32  <NA> F43  F431 F431
 [1723] F323 F330 F431 F431 F421 F431 F412 F432 F431 F432 F32  F432 F431 F412
 [1737] F412 F43  F430 F99  F32  <NA> F331 F438 <NA> F430 F412 F32  <NA> F410
 [1751] F332 F431 F431 <NA> F322 <NA> F431 F41  Z730 Z730 F412 F432 F32  F41
 [1765] F41  F43  F43  F430 F322 F40  Z563 F43  F329 <NA> F43  F431 <NA> F43
 [1779] F43  F412 F43  F43  F412 <NA> F431 F430 F320 F41  F32  F431 F141 F99
 [1793] F412 F411 F312 F321 F410 F410 F33  F43  F438 F412 F321 F32  F431 F329
 [1807] F43  F431 F411 Z730 Z730 F410 F410 F329 Z566 <NA> F431 F438 F321 <NA>
 [1821] F430 F329 F43  F32  F43  F431 F431 F412 F430 F43  F431 F412 F32  <NA>
 [1835] F322 F43  F411 F411 F41  F99  F438 F431 Z56  F323 <NA> F432 F432 F432
 [1849] F41  F32  F32  F411 F411 F410 F43  <NA> F32  F32  F431 F41  F413 <NA>
 [1863] F333 F32  F32  F43  F32  F41  <NA> F33  F32  <NA> F332 F329 F32  F321
 [1877] F431 F320 F320 F41  F10  F10  F33  F419 <NA> F312 F93  F32  F321 F330
 [1891] F41  F431 F411 F419 F412 F411 F430 F43  F321 F31  F322 F33  F430 F411
 [1905] F321 F431 Z566 F431 F99  F32  <NA> F430 F99  F432 F412 F430 F321 F33
 [1919] Z730 F99  F321 F321 F32  <NA> F431 F43  F320 F43  F22  F329 F99  F438
 [1933] F410 F412 F32  F43  F412 F410 F321 F06  F412 F43  F412 Z566 F432 <NA>
 [1947] Z730 F438 F43  F412 F42  F32  F431 F322 F432 F431 F412 F320 F32  F430
 [1961] F99  F99  F251 F321 F321 F412 F432 <NA> F412 F332 F99  <NA> Z730 F43
 [1975] F431 F320 <NA> <NA> F323 F331 F430 <NA> F430 F32  F410 <NA> F322 F432
 [1989] F29  F410 F412 F42  F33  F33  F430 F432 F438 F323 F43  F412 F99  F431
 [2003] F431 F322 F322 F314 F99  F430 F43  F43  F411 <NA> F412 F432 F430 F316
 [2017] F412 F19  F322 F331 F321 F413 F321 F321 F10  F322 F431 F432 F412 F410
 [2031] <NA> Z730 F331 F432 <NA> F431 F449 F41  <NA> F410 F432 F431 F32  F321
 [2045] F439 F412 F431 F432 F410 F432 <NA> F431 F430 F402 F431 <NA> F064 F99
 [2059] Y96  F321 F411 F99  F99  F412 F43  F430 F323 F32  F320 <NA> F412 F322
 [2073] F321 F412 F400 F432 F432 F432 F43  F332 <NA> F410 F412 <NA> F432 <NA>
 [2087] F431 F480 <NA> <NA> F43  F412 <NA> F321 Z730 F323 F430 F419 F431 <NA>
 [2101] Z654 F43  F321 F209 F321 F438 F438 F431 F412 F320 F323 F332 F43  F431
 [2115] F321 F43  F431 <NA> F430 F431 F32  R466 F43  F412 <NA> F32  F320 F43
 [2129] F410 <NA> F438 F432 F322 F432 F430 F32  F431 F33  F431 F431 F321 F432
 [2143] F99  F99  F32  F29  F431 F99  Z730 F32  Y04  F411 F41  <NA> F32  F411
 [2157] F331 F431 Z730 F321 F32  F41  F321 F43  F431 F401 <NA> F321 F32  F412
 [2171] F431 F99  <NA> F431 F439 F317 F430 F438 F349 F200 F412 F99  F43  F431
 [2185] F431 F320 F432 F322 Z730 F431 F329 F431 F432 <NA> F320 F321 <NA> F432
 [2199] I69  F430 F322 F321 F321 F432 T149 F431 <NA> <NA> <NA> <NA> Z565 F412
 [2213] F411 F410 F332 F331 F410 F29  <NA> <NA> F431 F338 F32  <NA> F432 <NA>
 [2227] F412 <NA> Z566 F432 F432 F449 F430 F432 F32  F432 F321 F412 F438 F322
 [2241] <NA> Z730 F316 F322 F432 F410 F438 <NA> <NA> F431 F412 F322 F43  F43
 [2255] F32  F32  F431 F431 <NA> F321 F430 V730 F419 F322 L270 F430 F322 <NA>
 [2269] F431 F431 F431 <NA> F431 F431 F41  F43  F322 F412 F411 F431 F32  F32
 [2283] F43  F432 F430 Z56  F431 F412 F32  F321 Z730 <NA> F32  F431 F431 F432
 [2297] F431 F322 <NA> F322 F411 F410 F432 F430 F431 F431 <NA> F332 <NA> F431
 [2311] F32  F322 F431 F43  F431 F41  F320 F321 F33  F431 F431 F320 F432 F43
 [2325] F322 F438 F43  <NA> F43  F488 F430 F412 F322 Z730 F41  F250 F432 F432
 [2339] F438 F459 F431 F431 F410 F431 F60  F380 F333 F321 F41  F329 Z730 <NA>
 [2353] F488 F410 F43  F430 F321 F322 F431 F432 F431 F431 F410 F432 <NA> F419
 [2367] F32  Z730 F431 F320 F43  F412 <NA> F43  F432 F412 F321 F413 <NA> F322
 [2381] F341 F43  F43  F329 Z730 F32  F40  F321 F29  F32  F329 F333 <NA> F431
 [2395] F430 F431 F431 F430 F431 <NA> F323 F321 F431 F332 F432 F422 F431 F322
 [2409] F320 F432 F332 H830 F43  F48  F322 <NA> F431 F432 F32  F322 F32  F431
 [2423] F412 F432 F438 F430 F400 <NA> F430 <NA> F431 F32  F321 F412 F412 F480
 [2437] F430 F412 F322 F328 F410 F99  F321 F410 F99  <NA> F99  F431 <NA> <NA>
 [2451] F431 <NA> F411 <NA> F431 F412 F480 F43  F432 F431 F412 F431 F431 F32
 [2465] F431 F412 F412 Y96  <NA> <NA> F09  F430 F430 F41  F430 <NA> F512 F439
 [2479] F32  F411 F411 F329 Z56  F322 F430 F99  F43  F331 F431 F480 F431 F431
 [2493] <NA> <NA> <NA> <NA> Z730 F32  F32  F431 <NA> F32  F321 F412 F411 F43
 [2507] F419 F321 F320 <NA> F32  <NA> F32  <NA> <NA> F430 F431 F430 <NA> F320
 [2521] F321 F431 F321 F322 F412 F42  F431 F32  F412 F431 F431 F430 F322 F432
 [2535] F43  F322 F321 F412 F43  F41  F412 F431 F431 F431 F340 F313 F313 F431
 [2549] Z564 F431 F32  F321 F431 Z730 F323 F32  F432 F432 F322 F32  F431 <NA>
 [2563] <NA> F431 Z730 F31  F431 F32  Z730 F412 F412 F431 F88  F43  <NA> F431
 [2577] F322 F432 <NA> F070 F332 F43  F411 F43  F43  F43  F412 F322 F322 F430
 [2591] F432 F43  F331 F432 F412 <NA> F33  F43  F412 F32  F431 F411 <NA> F32
 [2605] F431 A438 <NA> F488 F431 F99  F312 F332 F488 Y96  F430 F32  F431 F431
 [2619] <NA> F432 F430 F431 F430 F32  F43  F431 F40  F320 F32  F431 F410 F41
 [2633] F431 F430 F322 F322 F412 F32  F332 F43  F488 <NA> F432 F431 F431 F412
 [2647] F41  I119 F332 F410 F331 F412 F32  F43  F430 F431 F43  F43  F43  F43
 [2661] F410 F431 Z730 F432 F438 F431 F431 Z730 F322 F439 F400 F332 F32  F432
 [2675] F410 F432 F33  F420 F33  F431 F430 F432 F43  F412 F431 F33  F431 <NA>
 [2689] F430 <NA> F432 F238 F322 F412 F32  F332 F43  <NA> <NA> F411 F32  <NA>
 [2703] F431 F431 F322 F44  F44  <NA> F410 <NA> F431 F332 F322 F32  <NA> F33
 [2717] F431 <NA> F102 F488 F43  F432 F431 <NA> F31  <NA> <NA> F430 F43  F412
 [2731] F430 F431 F430 F412 F32  F332 F431 F99  F410 F430 F431 F432 F322 F512
 [2745] F432 F432 F431 F323 F321 F410 F431 F322 F331 F32  F32  F322 F430 F430
 [2759] F432 F32  E105 F438 F431 F321 F410 F432 F430 F431 F43  F431 F431 F438
 [2773] F322 F32  F408 F431 F431 F431 F431 F431 F401 Z730 F321 F432 F33  F332
 [2787] F329 F33  F412 F430 F431 F43  Z914 F322 F432 F321 F411 S432 F322 F430
 [2801] F421 F430 <NA> <NA> F329 F321 F432 F431 F431 F321 E10  F43  R45  F431
 [2815] F43  F432 <NA> F32  F430 F32  F33  F32  F317 F99  F408 F99  F431 F431
 [2829] F32  F438 F432 F321 F431 F438 F321 F431 F432 F41  F410 F43  F32  F421
 [2843] F43  F432 F431 F323 F318 <NA> F431 F41  F322 F43  F431 F43  F430 F431
 [2857] F431 F43  F41  Z730 F431 F333 F431 F438 F431 F432 F32  F431 F412 F40
 [2871] F320 F32  F33  F32  F331 F431 F32  F43  F432 <NA> F430 F431 F43  F41
 [2885] F320 S432 F321 Z566 F422 F412 F41  F432 F32  F333 <NA> F431 F41  F431
 [2899] F431 F322 R45  F91  F412 <NA> F432 F43  F331 F32  Z73  F32  F321 F41
 [2913] F32  F43  F73  F32  F431 F432 F431 F322 F322 F322 F320 F432 F432 F431
 [2927] F431 F43  F322 F431 F328 F43  F430 F430 F430 F430 F430 F430 F430 F430
 [2941] F331 F33  F410 F41  F32  F431 R457 <NA> F99  F99  F321 F43  F32  L431
 [2955] L408 F32  F438 F432 F32  F430 F431 F411 F431 Y96  F32  F43  F430 F321
 [2969] F419 F41  F412 F412 F321 F431 F431 F430 F412 F43  F431 F43  F430 F45
 [2983] F411 F431 F431 F431 F321 <NA> F431 F431 F411 F43  F43  F322 F438 F431
 [2997] F43  F412 F431 F320 F09  F431 <NA> F412 F432 F431 F431 F431 F322 F321
 [3011] F431 F32  F33  F323 F431 F43  F322 F432 F431 F320 <NA> F329 F480 F32
 [3025] F341 F411 F99  F438 F431 F431 F431 F419 F410 F320 F32  F431 <NA> <NA>
 [3039] F411 F431 F410 F431 F09  F09  F09  F09  Z730 Z730 F32  F431 F43  F33
 [3053] F41  F431 F431 F410 F430 <NA> F431 F431 F431 F432 F410 F41  F411 F431
 [3067] F431 F32  F412 F431 F320 F431 Z730 F432 F432 F431 F431 F431 F431 F412
 [3081] F488 F321 F431 F42  F431 F411 F431 F432 F432 F321 F421 F432 F431 F431
 [3095] F431 <NA> F431 F432 F322 F412 Y04  F438 <NA> F432 F322 F431 F431 F431
 [3109] Z730 F410 F43  F321 F418 F432 F431 F419 F401 F412 F431 F43  F32  F412
 [3123] F332 F32  F412 F332 F43  F431 F99  F431 F43  F410 F331 F411 F320 F431
 [3137] F321 F323 <NA> F43  F430 F32  F43  F32  F431 F431 F322 F438 F410 F412
 [3151] <NA> F431 <NA> F321 F410 F43  F201 F430 F430 F430 F412 F323 F322 F431
 [3165] F99  F321 F43  F32  F431 F321 F33  F431 F32  F409 F322 F320 F320 F321
 [3179] F33  F322 F321 F431 F32  F41  F432 F454 F313 F332 F321 F412 F431 F321
 [3193] Z730 F332 F412 F411 F412 F32  F09  F431 F431 <NA> F402 F300 F32  F43
 [3207] F411 F430 F412 F32  F411 F32  F32  F32  F432 F430 F43  F31  F32  F431
 [3221] F431 F322 F411 F43  F431 F431 F431 F431 F322 F321 <NA> F431 F322 F45
 [3235] F410 F32  F41  F431 F323 I256 F431 F412 <NA> F430 F431 Z566 F431 F431
 [3249] F431 F99  F410 F431 F431 F410 F411 F410 <NA> F431 F339 F323 <NA> F419
 [3263] F322 F488 F322 F411 F430 F412 F430 F32  F322 F32  F33  F331 F43  F99
 [3277] F431 F43  M545 F430 F430 F430 F430 F430 F430 F430 F430 F430 F430 F430
 [3291] F430 F32  F432 F323 Z73  F99  F410 F332 F99  F431 F431 F99  F412 <NA>
 [3305] F43  F32  F32  F431 F33  F332 F431 <NA> Z565 F431 F92  F438 F431 F431
 [3319] F430 F431 F412 F322 F43  F419 F431 M232 F322 F431 F32  F431 F431 F431
 [3333] F431 F432 F430 F322 F43  F431 F432 F258 <NA> F431 F431 F321 F99  F432
 [3347] F431 F43  F43  F408 F431 F438 F411 F32  F231 F431 <NA> F33  F43  F432
 [3361] F412 F605 F430 F321 <NA> F422 F329 F412 F438 F430 F431 F321 F431 <NA>
 [3375] F431 F332 <NA> <NA> F41  F432 F431 F43  F33  F410 F43  <NA> F412 F431
 [3389] F412 F432 F331 F323 F412 Z73  F412 F431 F432 F432 F43  F321 F432 F072
 [3403] F431 F41  F412 <NA> F412 F99  F411 F431 <NA> F432 <NA> F322 F411 F411
 [3417] F412 F412 F43  F32  F321 F322 Z730 F320 F412 F431 F431 F431 F431 F438
 [3431] <NA> F43  F32  F412 Z566 F412 F412 F430 F431 F431 F412 F43  <NA> F322
 [3445] F320 F431 F431 <NA> F438 <NA> F431 F438 F322 <NA> F411 F32  F431 F431
 [3459] F431 F41  F33  F32  F430 F99  F41  F432 F431 F412 F431 F432 F432 F512
 [3473] F32  F41  F43  F33  F412 F431 F322 F432 F431 F438 F431 F431 F333 F32
 [3487] F321 F438 F430 F332 F332 F32  F430 F43  F32  F99  F331 F99  F41  F32
 [3501] F43  F322 F43  F431 F431 Z730 F412 Z73  F438 F412 <NA> F321 Z730 F412
 [3515] F431 F32  F430 F32  F431 F332 F32  F323 F438 F322 F412 F431 F411 F43
 [3529] F41  F323 F43  F430 F412 F412 F412 F32  F431 F32  F438 F41  F332 F431
 [3543] F43  F431 F43  F410 F432 <NA> F412 F411 F43  F431 F431 F32  F412 F431
 [3557] F431 F432 F438 F432 F32  F431 F431 Z64  F32  F068 F99  F321 F43  F431
 [3571] F43  F340 F32  F410 Z566 F412 F220 F064 F43  <NA> Z730 F410 F431 F43
 [3585] Z566 Z565 F430 F488 F322 F322 F33  F322 F32  F438 F410 F431 F438 F411

**Averiguando integridade e disponibilidade dos estados para a variável 'Estado de Notificação':**

In [22]:
dados$SG_UF_NOT

    [1] 28 42 35 29 29 29 26 26 29 24 24 35 35 50 50 50 50 50 35 50 50 50 50 50
   [25] 35 35 26 28 29 26 35 35 35 35 42 35 35 29 31 29 17 23 23 25 35 50 29 26
   [49] 35 35 35 35 41 42 42 35 35 35 35 35 35 35 35 35 32 35 35 50 28 28 29 35
   [73] 35 26 24 24 35 14 42 35 35 31 35 35 50 28 28 28 28 28 28 28 28 35 35 35
   [97] 31 31 31 29 24 24 17 31 31 31 35 35 35 31 35 31 31 31 35 35 35 35 35 35
  [121] 35 35 35 50 42 28 28 35 28 28 31 31 31 29 17 17 35 35 31 29 35 31 31 31
  [145] 31 17 23 31 17 35 35 35 35 35 13 50 35 29 35 35 35 35 35 35 35 17 28 28
  [169] 35 31 42 42 42 35 35 35 35 35 35 31 31 31 31 35 31 35 29 35 35 35 35 35
  [193] 29 35 35 41 41 29 35 35 28 31 31 31 31 35 35 35 35 35 35 31 35 35 29 29
  [217] 24 24 42 35 31 31 35 23 23 42 35 35 35 35 35 35 35 42 23 23 31 31 31 31
  [241] 35 35 29 35 43 17 29 35 31 28 29 29 17 31 35 35 41 35 35 35 31 50 24 35
  [265] 35 35 35 35 35 31 31 31 31 31 31 31 31 31 41 29 50 35 35 31 31 41 28 17
  [289] 35 35 35 29 35 41 42 42 42 35 42 42 50 50 28 28 28 29 31 35 35 35 35 35
  [313] 31 35 31 23 35 35 35 33 23 23 29 41 35 25 31 43 31 31 35 35 35 31 31 35
  [337] 35 35 35 35 35 41 29 42 42 42 17 17 28 29 41 35 35 35 42 31 35 35 31 31
  [361] 31 31 31 35 43 31 31 29 31 29 35 35 43 50 50 42 35 33 35 17 17 35 31 29
  [385] 29 17 35 41 35 35 23 41 35 35 35 35 35 35 35 35 35 35 35 23 50 42 35 29
  [409] 29 25 29 23 50 29 35 14 17 31 41 35 26 31 23 35 29 29 23 29 42 23 51 51
  [433] 31 35 35 35 42 26 26 42 32 32 32 15 23 35 17 17 35 23 23 35 26 35 17 35
  [457] 17 35 35 29 28 35 29 29 29 29 35 24 35 35 35 29 29 29 28 50 35 35 24 35
  [481] 35 35 35 26 35 42 17 31 29 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
  [505] 41 35 35 17 31 35 42 28 42 29 33 41 29 29 23 41 35 29 29 29 26 23 42 50
  [529] 35 13 31 29 29 13 17 42 11 23 27 35 42 31 31 29 11 26 29 26 31 29 43 17
  [553] 43 24 50 41 24 50 42 24 24 35 31 35 29 29 29 50 29 43 35 33 33 33 33 33
  [577] 33 26 26 26 26 26 26 26 26 26 42 31 33 35 29 42 29 35 35 35 35 35 35 35
  [601] 23 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 23 35 26 35 43 31 17 35
  [625] 28 43 35 31 28 26 26 26 31 17 35 31 35 35 35 29 35 35 50 31 35 35 35 35
  [649] 23 28 52 52 52 35 35 23 28 42 23 42 31 35 26 26 26 26 35 42 29 29 17 35
  [673] 41 41 28 26 42 41 31 35 35 26 23 31 50 31 28 42 43 21 31 35 31 29 31 35
  [697] 25 31 13 13 13 13 13 13 41 35 35 35 13 13 13 42 13 51 29 29 29 41 31 31
  [721] 35 31 31 13 29 35 31 42 31 31 31 41 26 41 26 31 29 35 35 28 17 35 13 13
  [745] 35 52 50 23 31 31 31 31 31 31 31 31 31 13 52 13 13 31 23 26 35 42 35 42
  [769] 35 31 31 51 29 26 42 23 50 35 35 52 35 35 13 13 31 35 35 24 13 35 43 35
  [793] 35 31 31 31 35 35 35 35 35 35 35 35 35 42 43 43 43 35 26 35 31 31 43 43
  [817] 26 42 50 13 31 52 43 29 29 29 31 43 31 31 31 31 35 35 35 31 41 41 41 31
  [841] 35 29 31 50 35 35 31 31 35 21 33 35 26 31 31 31 31 31 35 52 35 26 31 31
  [865] 29 50 31 35 42 31 35 23 35 42 26 28 24 26 50 35 31 35 31 28 31 29 29 24
  [889] 26 41 24 35 33 31 35 42 31 35 31 31 42 35 11 35 31 35 31 35 52 26 25 35
  [913] 32 35 35 28 35 23 29 35 11 31 23 31 32 21 21 21 21 21 21 21 21 21 21 32
  [937] 32 42 31 24 31 35 31 31 29 35 35 35 29 35 35 35 28 43 31 31 29 11 11 11
  [961] 31 31 33 35 28 26 11 35 41 35 35 26 35 35 35 35 23 11 35 31 31 31 31 31
  [985] 31 26 35 11 50 31 51 32 24 26 50 50 11 11 11 31 31 31 31 31 31 42 29 29
 [1009] 26 31 31 33 42 31 35 35 26 31 31 31 31 31 52 24 29 29 26 26 29 31 35 35
 [1033] 29 13 41 35 13 13 31 41 17 24 24 32 31 31 42 33 35 35 35 35 35 43 23 26
 [1057] 31 35 43 43 32 29 31 35 35 35 35 17 35 35 35 35 29 35 35 35 35 35 35 24
 [1081] 31 23 50 35 35 35 26 26 35 26 35 35 35 35 35 35 35 35 35 41 26 35 31 26
 [1105] 42 35 35 31 31 31 31 26 26 31 31 31 31 29 26 35 50 31 28 32 32 32 35 42
 [1129] 29 50 35 32 32 42 29 31 35 32 29 29 35 29 29 41 41 31 31 31 31 42 42 29
 [1153] 35 35 26 41 41 31 31 31 42 41 35 35 28 35 29 35 29 24 41 41 31 31 31 23
 [1177] 35 35 35 23 35 24 31 31 31 31 33 42 31 26 35 26 35 31 31 31 35 50 29 31
 [1201] 29 35 42 41 26 35 35 32 35 35 35 35 35 35 29 32 35 31 23 35 15 35 31 26
 [1225] 17 26 35 23 28 42 29 35 35 23 26 26 23 41 52 42 26 26 35 35 28 35 35 52
 [1249] 52 24 29 35 35 26 33 35 31 31 25 26 35 35 25 35 43 35 13 11 28 31 31 31
 [1273] 31 35 42 35 50 31 35 31 31 31 35 35 42 35 31 32 35 35 28 31 41 17 23 31
 [1297] 35 29 41 32 32 24 23 15 31 31 23 33 35 35 35 35 32 29 15 35 26 26 26 26
 [1321] 32 41 35 33 25 15 35 35 31 26 35 13 29 26 35 28 29 35 52 26 26 26 35 29
 [1345] 31 31 31 31 31 31 31 31 31 25 31 42 26 35 31 26 35 14 41 35 26 26 35 29
 [1369] 29 35 35 35 35 35 42 35 41 23 26 35 35 35 35 35 35 31 31 42 26 35 35 16
 [1393] 15 35 35 33 29 35 24 31 26 50 35 31 31 35 35 35 23 23 23 24 31 31 31 35
 [1417] 26 52 23 23 35 24 52 35 24 35 31 35 32 35 41 41 41 41 35 35 31 35 31 17
 [1441] 52 13 42 35 31 35 29 29 31 26 35 13 32 29 29 31 35 26 52 29 31 35 23 24
 [1465] 24 24 31 23 23 35 31 35 31 35 35 35 35 23 23 35 35 42 23 23 42 13 13 52
 [1489] 29 31 31 23 31 35 26 29 41 23 35 42 31 41 35 35 50 23 41 41 31 31 33 41
 [1513] 50 42 13 35 41 29 41 35 17 23 35 23 41 41 41 33 33 29 29 41 41 31 41 13
 [1537] 53 31 31 31 31 31 31 31 31 35 35 31 23 25 35 35 35 41 26 35 35 35 31 31
 [1561] 35 29 35 26 31 41 31 29 29 29 26 35 26 26 31 26 42 41 31 31 29 23 35 26
 [1585] 31 31 31 29 35 35 35 35 29 29 25 50 42 23 26 26 35 23 33 25 31 29 23 26
 [1609] 23 42 25 32 24 29 33 42 24 26 42 42 35 35 23 50 35 24 24 33 23 35 35 35
 [1633] 24 28 25 26 35 35 23 24 35 35 26 35 26 35 35 52 52 35 35 25 35 26 35 35
 [1657] 35 23 52 35 31 35 42 23 35 50 13 26 29 31 35 15 35 25 31 35 35 35 35 35
 [1681] 50 42 24 24 35 31 35 31 29 29 35 35 29 42 42 35 41 35 35 35 35 35 35 42
 [1705] 35 35 17 31 52 52 31 26 24 23 25 33 31 23 27 17 31 31 24 29 31 31 31 26
 [1729] 23 31 17 35 33 31 31 26 24 42 42 23 35 35 35 24 35 31 31 31 35 35 41 42
 [1753] 31 42 35 35 29 35 35 31 35 26 35 35 35 31 31 31 51 35 23 35 23 31 42 42
 [1777] 35 31 31 31 31 31 31 29 31 31 29 35 35 35 43 29 29 31 26 35 31 29 31 42
 [1801] 31 35 35 35 26 35 42 26 35 32 32 32 41 35 41 35 31 42 31 35 31 35 35 35
 [1825] 24 31 35 29 35 42 35 35 43 35 31 29 35 35 31 32 35 42 31 35 35 31 29 26
 [1849] 35 35 35 35 35 35 42 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35
 [1873] 42 35 31 26 26 26 26 35 35 35 35 35 35 35 35 35 35 35 25 26 31 31 31 31
 [1897] 31 35 31 31 31 42 26 31 23 41 35 31 29 23 50 31 29 26 31 31 31 24 32 25
 [1921] 31 31 23 31 35 25 35 23 31 35 41 32 31 23 42 42 26 23 31 21 35 35 35 23
 [1945] 35 27 23 24 42 26 35 53 31 31 31 31 50 35 29 35 29 32 31 31 31 17 26 15
 [1969] 29 26 32 29 35 35 23 23 29 35 41 35 42 26 31 35 33 43 31 24 25 26 52 52
 [1993] 52 52 31 24 24 53 42 23 29 31 31 26 26 31 35 25 42 31 26 31 31 24 24 31
 [2017] 25 17 35 28 26 32 35 35 17 35 23 23 31 31 35 23 35 26 35 41 35 35 50 35
 [2041] 26 24 31 23 35 35 43 24 35 29 23 26 26 35 28 50 35 35 13 41 35 23 23 35
 [2065] 35 26 35 31 35 35 35 35 43 35 35 26 26 24 35 41 50 33 35 29 24 33 35 33
 [2089] 50 50 24 35 35 24 41 28 35 35 24 35 29 35 35 17 35 24 24 29 35 17 35 29
 [2113] 42 35 24 29 35 29 24 31 52 31 31 23 29 50 17 42 33 50 24 24 35 35 35 35
 [2137] 24 13 31 35 35 26 50 35 25 23 28 41 15 35 31 35 35 11 35 33 25 31 17 35
 [2161] 35 23 23 35 35 35 23 50 35 35 29 51 29 35 26 23 31 24 23 23 24 43 35 31
 [2185] 31 35 23 26 35 31 35 51 31 50 35 23 31 26 29 28 35 35 35 26 35 35 17 17
 [2209] 17 17 35 26 24 24 35 35 29 29 17 17 26 42 35 35 35 23 25 23 35 17 24 35
 [2233] 53 26 35 35 35 35 35 35 31 29 35 35 35 35 35 17 23 26 35 35 35 35 41 41
 [2257] 35 35 23 35 24 29 35 26 35 33 35 50 35 35 31 31 31 35 35 35 23 35 35 35
 [2281] 26 41 35 23 31 35 35 42 41 29 41 35 35 29 31 50 15 53 41 26 24 35 24 24
 [2305] 24 31 23 42 35 43 35 31 24 35 31 35 26 26 35 26 35 26 26 35 35 24 24 33
 [2329] 24 31 35 35 35 31 29 35 35 26 31 35 31 26 26 13 29 29 23 31 25 13 33 23
 [2353] 23 35 26 35 17 31 26 24 31 31 35 35 41 35 26 26 26 26 50 35 35 31 26 35
 [2377] 31 31 35 17 29 35 35 35 35 25 29 41 35 26 43 31 31 24 31 31 31 31 31 42
 [2401] 26 35 35 23 35 24 29 35 23 17 23 17 35 25 35 25 26 35 50 33 26 35 35 25
 [2425] 24 31 35 31 31 35 26 26 31 31 31 31 31 31 31 35 35 42 29 29 42 33 41 35
 [2449] 33 35 26 35 23 23 26 31 31 31 24 31 35 26 26 41 35 31 31 23 41 42 41 43
 [2473] 43 41 42 35 31 23 26 24 50 28 41 26 50 41 35 26 35 35 29 29 31 31 31 31
 [2497] 52 26 26 35 35 31 26 26 35 35 31 29 26 35 26 31 31 31 31 26 35 25 17 41
 [2521] 29 35 35 26 29 29 29 31 24 25 35 35 50 35 35 35 35 35 35 35 35 53 35 35
 [2545] 25 35 35 25 42 25 26 41 35 29 35 35 24 24 42 26 35 35 29 24 26 42 26 26
 [2569] 53 26 23 21 35 42 26 26 24 35 25 35 26 42 24 24 24 26 26 26 35 35 35 35
 [2593] 26 43 29 43 31 24 26 26 26 17 42 26 35 42 35 35 35 50 35 35 35 23 24 26
 [2617] 35 35 28 43 26 26 26 35 35 35 29 35 26 26 25 42 26 31 35 35 26 43 29 35
 [2641] 35 33 13 26 35 24 35 25 23 35 35 26 42 24 24 35 35 35 35 35 35 35 41 28
 [2665] 24 24 26 41 29 35 13 15 35 29 35 35 29 25 29 23 35 35 35 31 31 42 42 26
 [2689] 35 26 24 31 31 31 31 41 26 29 29 31 35 23 13 24 29 23 23 23 35 35 24 35
 [2713] 35 41 50 31 35 42 35 35 35 35 26 29 29 29 29 35 35 35 35 35 35 35 50 23
 [2737] 17 43 35 35 24 24 24 24 24 24 24 24 24 24 24 23 35 26 35 35 35 35 35 26
 [2761] 17 35 26 35 50 26 24 24 26 26 35 35 35 35 35 35 35 35 26 26 35 41 24 24
 [2785] 35 29 23 42 35 35 35 26 32 50 50 50 31 35 29 26 35 35 31 31 26 24 24 24
 [2809] 24 24 17 35 35 21 43 35 43 26 35 26 31 26 29 31 41 31 24 31 43 24 24 24
 [2833] 24 24 24 35 35 35 35 35 43 35 35 35 26 35 35 31 31 50 50 35 35 35 35 31
 [2857] 31 29 29 41 26 26 24 24 24 24 26 51 50 35 26 26 31 35 26 26 26 35 35 31
 [2881] 42 41 31 50 26 35 26 42 24 24 24 24 26 35 32 24 24 35 35 31 35 28 29 33
 [2905] 35 24 24 41 35 26 23 35 35 24 24 26 26 35 35 35 29 29 35 35 35 26 35 35
 [2929] 35 24 50 24 41 41 41 41 41 41 41 41 26 29 35 35 31 26 25 33 23 23 35 35
 [2953] 26 31 31 26 31 35 26 24 35 35 26 23 26 26 26 35 35 35 35 35 35 24 26 24
 [2977] 24 29 26 41 35 35 25 26 26 26 23 33 29 29 31 35 35 35 33 35 24 24 31 21
 [3001] 21 26 41 35 21 53 53 53 25 26 17 26 26 23 24 24 41 35 24 21 21 35 53 26
 [3025] 26 31 32 24 24 24 26 35 35 21 41 41 41 43 23 26 35 24 21 21 21 21 23 23
 [3049] 23 31 31 50 35 24 24 21 24 21 24 31 31 35 35 35 23 25 31 26 35 29 32 29
 [3073] 53 35 35 27 27 27 27 35 35 26 35 35 33 23 24 24 24 24 24 24 31 31 31 33
 [3097] 24 35 35 35 35 24 31 24 26 31 35 35 23 23 31 24 24 24 31 35 31 25 31 35
 [3121] 35 35 35 35 35 35 35 35 43 24 41 15 29 31 31 35 17 23 35 23 35 50 23 41
 [3145] 31 43 35 24 25 35 17 31 29 23 31 26 35 23 29 29 35 23 29 31 25 25 42 35
 [3169] 31 42 41 35 35 35 29 29 26 35 35 35 35 31 26 43 43 43 31 26 35 35 31 42
 [3193] 29 25 35 28 43 41 23 29 21 52 35 33 26 23 23 24 29 26 23 35 26 26 35 35
 [3217] 31 26 31 26 26 23 23 31 24 24 24 24 26 26 26 26 25 23 35 31 31 31 31 17
 [3241] 26 26 43 42 33 26 26 26 33 31 35 35 24 26 21 26 25 26 23 23 33 43 43 41
 [3265] 31 31 24 24 24 25 25 25 25 25 23 31 31 26 13 41 41 41 41 41 41 41 41 41
 [3289] 41 41 41 33 33 33 33 33 33 33 29 41 31 31 26 33 35 52 52 24 25 35 24 43
 [3313] 31 31 26 24 24 24 24 24 24 26 26 50 26 29 26 32 31 24 24 24 24 35 25 25
 [3337] 42 35 35 50 33 31 33 26 31 50 31 35 35 29 24 24 24 25 25 33 35 29 29 26
 [3361] 50 41 41 43 29 29 35 25 24 24 24 24 24 41 35 41 41 41 41 41 26 35 41 41
 [3385] 31 33 35 35 26 24 24 24 31 31 31 35 35 35 31 43 24 24 24 31 31 31 31 31
 [3409] 41 24 31 24 23 25 29 29 29 35 35 26 26 26 23 24 24 24 24 24 24 24 33 31
 [3433] 26 29 41 31 31 24 24 24 35 35 33 26 26 31 31 33 24 33 27 24 26 35 25 26
 [3457] 32 29 32 31 35 29 25 23 35 24 24 24 35 35 35 29 50 52 26 26 26 31 26 24
 [3481] 24 24 24 35 25 35 24 24 24 26 26 35 35 26 41 23 26 23 35 35 35 26 25 31
 [3505] 31 43 35 32 24 35 17 35 35 26 31 26 41 35 24 26 26 26 24 31 25 31 31 35
 [3529] 35 25 26 29 15 15 35 33 33 35 24 24 35 31 35 31 31 31 25 27 25 35 41 33
 [3553] 43 32 25 35 35 24 24 24 35 31 31 41 35 35 23 24 41 31 35 35 35 31 31 31
 [3577] 31 31 35 35 35 25 29 43 31 31 35 29 25 25 25 25 25 24 24 24 24 24 24 26
 [3601] 29 29 29 25 41 35 24 32 31 26 35 41 35 23 24 24 17 31 31 35 35 41 35 43
 [3625] 25 35 35 24 24 24 24 24 24 24 27 35 23 23 35 24 29 35 23 29 35 31 24 26
 [3649] 41 24 24 24 35 24 29 26 25 25 25 23 35 43 43 23 23 23 23 23 26 29 35 24
 [3673] 24 24 31 42 35 25 25 26 35 25 50 35 29 26 31 41 35 43 35 24 35 29 35 28
 [3697] 25 25 25 35 35 35 26 26 17 31 31 31 31 24 42 43 35 35 35 35 35 31 35 28
 [3721] 35 35 25 31 35 35 43 29 32 35 29 35 35 26 11 43 24 29 11 35 35 24 24 23
 [3745] 24 24 24 41 41 35 35 35 35 35 35 25 25 25 31 31 31 33 35 35 35 35 35 35
 [3769] 35 35 35 35 33 28 35 35 31 29 35 35 33 50 35 35 35 35 25 26 24 24 24 24
 [3793] 24 24 31 25 25 50 29 29 31 31 31 35 31 31 31 43 28 26 35 35 26 35 31 35
 [3817] 26 29 29 29 35 35 35 24 24 24 29 35 29 17 35 35 25 25 25 25 25 29 29 29
 [3841] 35 29 35 31 15 35 35 29 29 35 35 29 35 35 31 24 29 26 26 35 23 29 24 24
 [3865] 24 24 50 25 25 43 24 35 27 24 29 41 35 35 35 35 35 35 24 24 33 35 13 24
 [3889] 24 24 24 25 29 31 41 43 31 33 42 24 26 35 29 29 17 42 33 31 31 31 35 15
 [3913] 23 35 35 35 42 23 15 24 24 24 24 24 24 35 35 35 35 29 26 35 26 24 42 24
 [3937] 35 35 23 35 23 23 23 23 43 35 35 26 50 50 24 24 24 24 25 25 26 35 27 23
 [3961] 21 24 26 29 35 24 24 24 35 26 23 35 13 13 13 26 29 31 31 21 26 31 24 35
 [3985] 28 29 23 43 24 26 42 31 24 24 24 24 25 25 25 43 23 23 26 35 13 13 26 24
 [4009] 13 24 24 35 35 35 27 24 25 31 26 50 35 35 25 24 24 24 35 35 35 35 43 35
 [4033] 13 41 41 28 28 33 35 23 31 31 25 25 24 24 24 24 24 35 26 26 24 29 23 26
 [4057] 29 35 24 24 43 35 27 23 31 41 35 35 35 25 29 24 24 24 24 24 43 41 26 35
 [4081] 35 35 23 35 29 35 35 35 23 35 26 35 23 35 29 17 17 17 35 31 31 23 23 23
 [4105] 23 31 31 24 24 35 24 24 24 24 24 35 24 24 35 27 23 29 25 31 23 35 43 43
 [4129] 17 31 23 31 35 41 31 23 29 35 41 25 25 25 29 35 31 35 31 31 26 23 35 35
 [4153] 35 29 29 50 13 31 35 35 31 26 31 26 26 35 33 35 31 31 35 29 31 43 43 23
 [4177] 23 23 25 25 43 26 31 35 41 31 33 53 35 43 29 51 29 31 31 35 25 25 35 23
 [4201] 23 26 35 35 35 32 35 35 41 35 35 35 35 35 35 31 50 29 35 35 35 35 24 24
 [4225] 24 24 24 25 25 25 25 35 35 53 35 29 24 26 42 35 28 28 13 35 29 29 35 35
 [4249] 50 27 23 29 29 24 24 24 43 50 32 52 35 35 35 35 35 29 32 13 35 35 35 35
 [4273] 31 31 31 31 31 29 24 29 23 17 31 24 23 31 31 31 25 25 25 25 25 29 52 27
 [4297] 27 35 35 35 43 24 13 35 35 42 43 43 24 24 24 31 35 35 13 13 29 27 26 24
 [4321] 53 53 35 31 25 35 24 24 43 24 24 24 35 35 35 25 50 29 24 23 23 31 29 29
 [4345] 29 24 24 24 35 23 23 23 23 23 23 23 31 26 24 24 24 24 23 23 23 26 35 26
 [4369] 31 31 31 26 31 53 53 26 13 31 31 35 35 29 32 35 35 31 35 35 13 41 41 51
 [4393] 52 35 29 53 24 24 24 24 24 24 24 24 35 35 35 41 33 35 31 26 33 33 41 41
 [4417] 41 26 35 41 41 41 41 31 41 35 35 41 41 41 41 31 27 43 35 35 41 41 41 35
 [4441] 35 35 35 35 35 24 24 29 29 41 41 41 35 42 29 41 41 50 41 41 41 41 35 24
 [4465] 31 31 42 31 31 31 32 23 35 24 24 24 24 31 23 35 24 35 35 33 26 24 26 31
 [4489] 35 35 35 24 31 23 24 24 24 24 24 24 29 21 26 24 24 24 35 35 43 26 26 35
 [4513] 24 35 35 41 35 21 31 25 41 35 35 42 24 31 26 35 31 32 32 21 26 29 27 35
 [4537] 35 35 35 29 31 31 24 24 24 35 35 31 35 31 26 31 35 35 35 35 35 31 29 32
 [4561] 29 26 35 35 26 35 28 35 13 13 29 35 31 31 29 31 35 35 23 27 29 35 35 35
 [4585] 35 35 24 31 35 35 35 35 35 24 24 23 35 23 43 41 35 35 35 43 26 31 42 23
 [4609] 23 50 50 50 50 50 50 26 29 29 29 35 35 24 24 35 35 35 31 26 35 35 35 35
 [4633] 35 43 35 35 35 42 23 29 13 29 24 24 24 24 26 35 35 26 13 35 35 35 13 26
 [4657] 35 41 41 35 43 43 35 35 35 43 35 35 35 29 43 52 35 35 35 29 26 31 33 13
 [4681] 35 35 35 35 24 24 24 24 24 24 24 31 43 32 35 13 31 26 26 29 29 35 43 43
 [4705] 35 35 23 35 35 35 35 14 26 31 35 35 35 35 35 35 35 35 35 35 43 24 35 29
 [4729] 23 26 42 43 43 26 32 35 42 43 35 31 31 31 31 31 31 31 31 31 26 35 17 35
 [4753] 23 43 31 31 35 29 35 41 26 31 26 17 17 41 35 43 43 31 41 29 35 35 43 35
 [4777] 43 23 15 31 43 43 31 29 35 35 35 35 26 23 31 35 43 29 29 42 42 26 41 32
 [4801] 23 13 35 26 23 35 35 35 35 33 26 35 43 31 35 28 35 31 35 29 28 31 26 13
 [4825] 23 27 29 31 17 28 41 31 24 24 24 24 35 15 15 15 28 43 43 26 31 26 35 35
 [4849] 41 31 23 43 17 27 35 35 26 23 26 43 35 35 35 35 31 26 29 31 35 35 31 31
 [4873] 31 29 35 50 29 24 24 24 41 26 26 15 35 35 41 43 35 35 41 41 23 13 35 35
 [4897] 35 35 26 35 31 31 31 31 35 31 26 35 29 43 43 43 29 31 31 23 35 35 35 24
 [4921] 24 24 24 24 24 23 35 35 35 35 27 11 27 41 26 35 35 50 26 31 31 43 35 35
 [4945] 35 35 35 35 35 29 27 24 24 24 27 26 35 35 35 31 50 35 31 23 15 31 31 35
 [4969] 23 43 35 35 26 35 50 52 29 33 33 41 41 35 23 33 33 33 33 33 33 35 29 35
 [4993] 35 35 35 35 50 35 24 35 35 35 35 35 43 26 26 35 35 35 43 33 27 33 32 29
 [5017] 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 29 29 42
 [5041] 13 13 13 35 35 35 35 35 41 35 33 26 33 27 31 35 35 35 26 35 31 35 29 26
 [5065] 43 35 35 35 35 43 17 35 27 27 52 35 33 35 23 35 43 13 35 23 52 31 35 35
 [5089] 31 35 35 35 35 23 35 35 42 35 35 27 26 31 35 35 35 35 35 33 35 35 35 35
 [5113] 35 35 35 26 35 31 35 35 35 35 35 35 31 27 17 13 26 35 41 23 26 13 35 24
 [5137] 31 31 23 23 43 35 35 17 35 35 35 35 42 31 31 35 27 35 35 35 35 35 42 26
 [5161] 29 26 31 17 33 43 35 31 31 35 35 35 31 42 43 35 35 35 35 35 31 35 29 35
 [5185] 35 35 31 35 35 29 31 31 35 43 43 43 31 35 35 35 35 17 17 31 31 43 24 24
 [5209] 24 35 23 31 27 32 26 26 31 35 26 26 35 35 43 31 42 35 35 35 17 43 23 26
 [5233] 35 35 26 42 26 35 35 35 35 35 35 35 35 35 35 31 26 26 26 35 35 35 35 35
 [5257] 26 35 29 35 35 35 35 35 33 17 31 35 35 23 31 35 35 26 24 24 24 24 24 24
 [5281] 31 27 11 24 35 35 35 23 35 35 43 31 43 31 33 35 35 35 35 35 35 35 35 35
 [5305] 51 26 35 35 35 35 33 25 41 31 24 24 24 24 24 24 43 26 26 31 42 35 35 31
 [5329] 28 13 24 24 35 35 35 35 35 35 35 26 43 24 24 24 24 35 35 35 35 24 35 35
 [5353] 35 23 29 17 31 43 43 43 24 24 24 24 24 24 35 35 35 35 17 24 23 35 23 43
 [5377] 43 33 35 24 24 35 35 27 23 32 24 24 24 24 24 24 24 24 31 31 31 31 17 17
 [5401] 24 31 31 31 31 31 24 24 24 24 24 24 35 35 41 35 11 35 35 35 35 35 29 35
 [5425] 35 35 35 35 24 31 35 35 35 35 35 35 35 35 35 35 35 35 35 43 35 35 31 35
 [5449] 17 17 35 35 26 35 42 35 17 25 35 24 52 52 29 29 41 23 27 31 31 35 52 29
 [5473] 24 24 24 24 24 35 23 31 35 24 24 24 24 24 24 24 23 43 35 35 35 35 35 35
 [5497] 43 29 29 24 24 24 24 24 24 31 31 43 24 24 35 35 35 35 35 35 24 24 24 24
 [5521] 24 24 43 33 35 43 24 28 43 26 31 31 31 32 31 35 35 35 35 35 26 35 31 35
 [5545] 35 43 32 31 17 43 35 31 21 26 27 35 43 17 31 27 35 35 35 33 13 33 31 35
 [5569] 23 29 24 24 24 24 24 24 24 24 42 24 31 35 35 31 27 31 28 31 29 31 31 23
 [5593] 41 29 35 35 31 26 29 33 43 43 23 43 26 43 31 42 17 15 17 35 35 35 24 35
 [5617] 35 23 35 35 26 35 35 35 29 17 43 35 35 43 43 43 43 31 31 23 52 35 24 24
 [5641] 41 31 41 31 31 31 31 32 31 29 28 35 26 28 35 27 35 35 29 42 24 24 24 31
 [5665] 33 35 31 31 41 26 17 29 31 32 27 31 35 43 27 31 26 29 50 43 43 35 27 26
 [5689] 27 27 41 35 35 31 35 42 31 42 26 26 26 17 27 27 31 27 29 35 26 35 35 35
 [5713] 15 35 31 35 35 32 24 24 24 24 29 31 43 26 32 35 35 35 27 35 35 35 35 35
 [5737] 17 26 41 24 24 24 24 24 31 35 26 26 24 24 31 35 35 31 35 33 41 35 27 33
 [5761] 35 27 31 43 33 33 33 31 31 35 35 31 24 31 35 43 35 42 35 35 50 31 31 43
 [5785] 29 35 35 27 43 32 26 26 24 24 35 35 35 35 35 43 32 35 26 50 33 33 26 26
 [5809] 29 35 31 27 31 31 31 43 24 24 43 31 26 35 35 35 27 33 31 29 27 31 26 31
 [5833] 31 33 27 27 31 31 43 43 43 35 35 35 33 24 24 24 24 24 35 35 35 35 35 35
 [5857] 33 33 33 33 42 35 35 35 35 35 35 35 35 21 33 33 33 33 33 26 31 31 35 35
 [5881] 35 35 35 13 13 35 27 27 27 27 27 27 27 24 24 24 24 23 33 33 33 33 35 43
 [5905] 35 26 26 33 33 33 33 33 33 33 33 33 33 35 35 50 33 33 33 33 33 35 29 43
 [5929] 33 33 33 33 33 33 33 33 33 33 33 33 33 31 33 33 33 33 27 27 27 27 27 27
 [5953] 24 24 24 35 35 35 13 29 33 33 33 33 33 33 43 43 35 26 42 31 35 50 42 31
 [5977] 29 35 35 35 41 41 26 35 29 41 43 35 35 43 43 43 43 43 43 43 43 35 35 43

_A base representa os casos notificados formalmente ao sistema de vigilância nacional, sabendo que o volume real de indivíduos com Burnout tratados por psicólogos e psiquiatras particulares/de convênio médico está altamente sub-representado nesses números._

In [26]:
# 1. Vetor nomeado para servir de "dicionário" de tradução
tradutor_uf <- c(
  "11" = "RO", "12" = "AC", "13" = "AM", "14" = "RR", "15" = "PA", "16" = "AP", "17" = "TO",
  "21" = "MA", "22" = "PI", "23" = "CE", "24" = "RN", "25" = "PB", "26" = "PE", "27" = "AL",
  "28" = "SE", "29" = "BA", "31" = "MG", "32" = "ES", "33" = "RJ", "35" = "SP", "41" = "PR",
  "42" = "SC", "43" = "RS", "50" = "MS", "51" = "MT", "52" = "GO", "53" = "DF"
)

In [32]:
tabela_Burnout <- dados %>%
  mutate(
    UF_Codigo = trimws(as.character(SG_UF)),
    UF_SG = tradutor_uf[UF_Codigo],
  ) %>%
  filter(
    DIAG_ESP   == "Z730"
  ) %>%
  group_by(UF_SG) %>%
  summarise(Casos = n(), .groups = "drop") %>%
  arrange(UF_SG)

head(tabela_Burnout, n = Inf)

   UF_SG Casos
1  AC      4
2  AL      8
3  AM      2
4  BA    238
5  CE     64
6  DF      6
7  ES      6
8  GO      4
9  MA      7
10 MG    314
11 MS     22
12 MT      7
13 PA     11
14 PB     43
15 PE     47
16 PR     21
17 RJ     96
18 RN     51
19 RO     11
20 RR      2
21 RS     89
22 SC     78
23 SE     22
24 SP    462
25 TO     11

Podemos verificar que não há registros referentes nem à Piauí (**PI**) nem à  Amapá (**AP**) para a base de dados utilizada.

# Selecionar as variáveis de interesse e tratar a variável de 'Estado De Notificação':

In [37]:
tabela_Burnout <- dados %>%
  select(FONTE_ANO, DIAG_ESP, SG_UF, SIT_TRAB, ID_OCUPA_N, CNAE, UF_EMP,
  TERCEIRIZA, NUTEMPORIS, TPTEMPO, AFAST_DESG, AFAST_TRAB, CAPES, EVOLUCAO) %>%
  mutate(
    UF_Codigo = trimws(as.character(SG_UF)),
    UF_SG = tradutor_uf[UF_Codigo],
  ) %>% select(-SG_UF, -UF_Codigo) %>%
    relocate(UF_SG, .after = DIAG_ESP) %>%
  filter(
    DIAG_ESP   == "Z730"
  )
# Exibe o resultado final com os dados tratados mediante dicionário:
#print(tabela_Burnout, n = Inf)

#saveRDS(tabela_Burnout, file = "work/dados_tratados_sinan.rds")
#tabela_Burnout <- readRDS('work/dados_tratados_sinan.rds')

head(tabela_Burnout)

  FONTE_ANO DIAG_ESP UF_SG SIT_TRAB ID_OCUPA_N CNAE  UF_EMP TERCEIRIZA
1 ano_10    Z730     SP    01       513425     NA    35     2
2 ano_10    Z730     PR    01       239405     NA    41     2
3 ano_11    Z730     MT    04       411010     NA    51     2
4 ano_11    Z730     RO    04       223405     NA    11     2
5 ano_11    Z730     BA    07       410105     NA    NA     2
6 ano_11    Z730     PE    04       331105     05126 26     2
  NUTEMPORIS TPTEMPO AFAST_DESG AFAST_TRAB CAPES EVOLUCAO
1 5          3       1          1          1     3
2 4          NA      2          1          1     3
3 20         4       1          NA         1     NA
4 5          4       2          2          1     3
5 0          NA      1          1          1     3
6 20         4       1          NA         1     4